### ISSUE TITLE
Image Pack Locations

### ISSUE THREAD

**Issue by math0ne** [kbuffington/Georgia#1]
This is awesome man!  Any hints on how to get the label images working?  What specific meta data does it use?  Do the image packs go in sub directories within the images directory?

**Comment by kbuffington** [comment]
Your image folder should be setup like [this](https://i.imgur.com/MU6sps1.png).

The theme checks both %theme% and %publisher% fields for determining what labels to show (it takes all labels from both fields and removes duplicates). If you're using a different field for labels, let me know and I can add it to the next release, or you can add it yourself to the tf.labels array in globals.js.

It's also pretty smart about finding the label images. For example, `Island.png` will be used for "Island", "Island Records", "Island Recordings", and "Island Music"... basically any common variation of a label string.

**Comment by math0ne** [comment]
Awesome man, got it working, great work with the theme.
