### ISSUE TITLE
Last.fm logo glitches on larger play counts

### ISSUE THREAD

**Issue by KatyLB** [kbuffington/Georgia#10]
It falls off the side and onto the top of the album art and also increases in size.

See the below:

![image](https://user-images.githubusercontent.com/37089178/58362957-3b33fb00-7e95-11e9-84ca-6685b39db636.png)

I can replicate this on any track that's sending the bar tally that far out. Windows 10, foobar2000 v1.3.4, large screen and the theme is full width.

**Comment by Artins90** [comment]
On a 4K display it's even worse, it becomes huge
<img width="1409" alt="Capture" src="https://user-images.githubusercontent.com/28777957/62827771-e6239d80-bbd6-11e9-9c7c-f08497e5411d.PNG">

**Comment by kbuffington** [comment]
This should be fixed now in v1.1.0. Let me know if you still have problems!
