### ISSUE TITLE
Sorting by DATE tag instead of year?

### ISSUE THREAD

**Issue by ghost** [kbuffington/Georgia#100]
I was wondering if it would be possible to add an option to sort by the DATE tag? Sorting by year in the library messes up the order which would make this feature double-useful. Many thanks for this theme btw, it's my favorite so far 👍

**Comment by kbuffington** [comment]
Are you referring to sorting in the Library panel when using the "Album Artist ordered by DATE" view?

**Comment by ghost** [comment]
Damn, I'm sorry for taking so long to get back to you, life's been busy. Yes I meant that

**Comment by kbuffington** [comment]
Sorry, I didn't see you respond at first 😃

Sorting of results is controlled by `settings.defaultSortString` in georgia-config.jsonc. By default this value is:
```
defaultSortString: '$if2(%artist sort order%,%album artist%) $if3(%album sort order%,%original release date%,%date%) %album% %edition% %codec% %discnumber% %tracknumber%',
```
It will look for in order: %album sort order%, %original release date% then %date%, and sort by one of those after sorting by artist. The playlist and library tree should always be sorted by this value, regardless of what is displayed. If you have full dates like "1985-04-25" it will use those to sort, even though "1985 - Cool Album" is shown in the library.

If that's not what you're seeing, please show me some examples of where it's going wrong.

**Comment by ghost** [comment]
Thank you very much for the clarification!
