### ISSUE TITLE
Multi-value genre display not working consistently

### ISSUE THREAD

**Issue by ReK42** [kbuffington/Georgia#103]
For some reason the display of the multi-value genre tag is not working correctly all the time. In the screenshot below I have two albums with identical genre tags, but they are displayed differently in the playlist view: one is correctly shown with the fancy delimiters, the other shows a simple string representation.

![2021-05-16_23-13-55](https://user-images.githubusercontent.com/4775937/118440672-ddf66d00-b69c-11eb-9fdd-c0ca06247919.png)

**Comment by kbuffington** [comment]
This is a problem with the file itself. I would remove the genre tags from those files, Apply changes, then re-paste them in. Then everything should appear correctly.

**Comment by kbuffington** [comment]
Closing this as there's been no further discussion.
