### ISSUE TITLE
Feature suggestion: automatic dark mode

### ISSUE THREAD

**Issue by magnificar** [kbuffington/Georgia#105]
I'm using Auto Dark Mode to change Windows from light to dark mode at every sunset. I know this is a very niche request (and as I'm not a coder, I have no idea how hard that would be to implement) but it would be really cool if Georgia followed that, changing from light to dark along with Windows.

**Comment by kbuffington** [comment]
This would be cool, but with a little cursory digging it appears that the APIs Win10 uses to enable Dark Mode are not fully documented and the ones that are are not exposed at all through FSM. Unfortunately there's no way to get this information to Georgia.
