### ISSUE TITLE
Lyrics won't show up

### ISSUE THREAD

**Issue by Rafee-M** [kbuffington/Georgia#107]
Keep getting "For %LYRICS% or %UNSYNCED LYRICS% to always display properly you edit LargeFieldsConfig.txt and comment out or remove those specific entries under 'fieldSpam' "

After removing the entries the error keeps popping up and yes the lyrics are in the file itself 
![image](https://user-images.githubusercontent.com/69535896/121191013-6677c000-c88d-11eb-8bd3-fc74cc426b30.png)
![image](https://user-images.githubusercontent.com/69535896/121191039-6aa3dd80-c88d-11eb-9587-b29827320416.png)
![image](https://user-images.githubusercontent.com/69535896/121191056-6e376480-c88d-11eb-9d77-056776e09ef2.png)

**Comment by Rafee-M** [comment]
Edit: After editing LargeFieldsConfig.txt again and adding the lyrics tags under 'List of basic meta fields' -

fieldBasic=lyrics

fieldBasic=unsynced lyrics

The lyrics show up, but they aren't synced i.e it doesn't highlight the current line it's playing. According to the wiki, Georgia seems to look at the file first of lyrics and there's no way to force the .lrc files

**Comment by kbuffington** [comment]
If there's no timestamps in the lyrics, there's no way to highlight the currently playing line. It's just gonna scroll as it goes.

Are you saying you've got embedded lyrics, and also .lrc files for the same songs, and the .lrc's aren't being used?

**Comment by Rafee-M** [comment]
Yes, exactly. I want to use the external .lrc files instead of the embedded lyrics 
![image](https://user-images.githubusercontent.com/69535896/121294012-7c799500-c90e-11eb-8bf0-a7bcb35f4912.png)

**Comment by Rafee-M** [comment]
Changed the `lyricFilenamePatterns` array's 4th pattern a bit and it works now
                "%title%",
		"%artist% - %title%",
		"%artist% -%title%",
		"%tracknumber% - %title%",
		"%tracknumber%. %artist% - %title%"
