### ISSUE TITLE
Jscript panel crash when scrolling the playlist quickly on a 4K screen

### ISSUE THREAD

**Issue by Artins90** [kbuffington/Georgia#11]
Error: JScript Panel v2.1.4 (Georgia by Mordred)
JavaScript runtime error:
LogicError: 
first_item_to_draw can't be null!

File: E:\Users\Artins\Desktop\foobar2000\georgia\js\CaTRoX_QWR\Common.js
Line: 262, Col: 9
<source text only available at compile time>

I can replicate this crash every time, just grab the scroll bar and pull it down quickly.
Probably the play list needs to include a large enough number of albums, 50 albums should suffice.

**Comment by kbuffington** [comment]
I literally just released an updated version which I think fixes this problem. Let me know if it goes away after you update.

**Comment by Artins90** [comment]
I tried to load it but it's returning the following error upon launching foobar, the skin doesn't load:

JScript Panel v2.2.2.2 (Georgia by Mordred)
JavaScript runtime error:
Unable to get property 'paint' of undefined or null reference
File: C:\Program Files\foobar2000\georgia\js\CaTRoX_QWR\Panel_Playlist.js
Line: 753, Col: 13

**Comment by kbuffington** [comment]
Wild. For now, you can stop that error from occurring by going into the properties and changing `Display playlist on startup` to `false`. I'll figure out how to stop that from happening soon.

**Comment by kbuffington** [comment]
If you really want to keep that option selected, go to line 1549 of georgia-main.js and add this code block:
```
	if (pref.start_Playlist) {
		displayPlaylist = false;
		setTimeout(function () {
			displayPlaylist = true;
			playlist.on_size(ww, wh);
			RepaintWindow();
		},30);
	}
```
That'll be the fix included in v1.1.1, unless I can find something better.

**Comment by Artins90** [comment]
Thank you for the hotfix, I was able to load the skin after adding the code.
The bad news is that I got a new error after starting the playback of a song: 
JScript Panel v2.2.2.2 (Georgia by Mordred)
JavaScript runtime error:
Unable to get property 'setColors' of undefined or null reference
File: C:\Program Files\foobar2000\georgia\js\themes.js
Line: 101, Col: 5

**Comment by kbuffington** [comment]
That's weird. I can't reproduce. Are you using embedded artwork? Is this a streaming source?

Replace line 101 with this and see if it works then: 
```
	if (str.timeline) {
		str.timeline.setColors(theme.darkAccent, theme.accent, theme.lightAccent);
	}

```
You might have issues with the timeline colors being off though.

**Comment by Artins90** [comment]
They are flac files from the local HDD.
There are some tracks with embedded artworks but it happens even when playing tracks without any.

The second hotfix fixed the issue and timeline colors look ok.
I am going to attach my entire foobar folder, it's in portable mode. 
I uploaded it before applying the second hotfix you provided, so it should crash when you hit play, it might help you replicate and identify the issue.

The scrollbar issue is gone so I think we can close this one.
We can continue to discuss the crashing issue when playing a track in the issue report #12

[foobar2000.zip](https://github.com/kbuffington/Georgia/files/3489868/foobar2000.zip)

**Comment by kbuffington** [comment]
Thanks for the zip. I was able to reproduce this with embedded artwork, and ALSO with regular artwork when stopping play. Just triple checking the fixes to make sure things are kosher.
