### ISSUE TITLE
Incorrect Play, Stop, Reverse, Forward icons

### ISSUE THREAD

**Issue by sumitautade** [kbuffington/Georgia#113]
Play, Stop, Reverse, Forward, etc. icons appearing incorrectly.

https://imgur.com/a/1MJu37z

**Comment by dwmartin0906** [comment]
Hi.  This appears to be the same issue as #110, Transport buttons font breaks.   Be sure you have all the fonts in the georgia\fonts folder installed, particularly the Guifx v2 Transports.ttf font, and that you restart Foobar after installing the fonts.  If you have already installed them, please try re-installing them and restarting Foobar just to be sure.

**Comment by sumitautade** [comment]
Okay, it worked after installing Guifx v2 Transports.ttf. Thanks!
