### ISSUE TITLE
Issue when playing a song

### ISSUE THREAD

**Issue by Fuyucch1** [kbuffington/Georgia#12]
Thanks for the amazing update !
I encounter this issue when I click on a song to play it : 

`JScript Panel v2.2.2.2 (Georgia by Mordred)
JavaScript runtime error:
Unable to get property 'setColors' of undefined or null reference
File: C:\Users\Freed\AppData\Roaming\foobar2000\georgia\js\themes.js
Line: 101, Col: 5`

Hope it can help you improve it, and as always, thanks for your amazing work :D

**Comment by Fuyucch1** [comment]
#11 Solution provided here works. Only using embedded artworks btw :D

**Comment by kbuffington** [comment]
Is foobar in portable mode for you?

**Comment by kbuffington** [comment]
Should be fixed in v1.1.1
