### ISSUE TITLE
First running worked ok, then I closed it, added the image packs, run for 2nd time and...

### ISSUE THREAD

**Issue by bleuge** [kbuffington/Georgia#13]
```
JScript Panel v2.2.2.2 (Georgia by Mordred)
Error en tiempo de ejecución de JavaScript:
No se puede obtener la propiedad 'setColors' de referencia nula o sin definir
File: C:\Users\xxx\AppData\Roaming\foobar2000\georgia\js\themes.js
Line: 101, Col: 5
```
JavaScript runtime error:
Cannot get property 'setColors' of null or undefined reference
File: C:\Users\xxx\AppData\Roaming\foobar2000\georgia\js\themes.js
Line: 101, Col: 5

AFAIK, Paths are ok, script engine is chakra, ... I follow the installation instructions line by line 
Thanks for this theme, it shows soo beatiful. Also Codec logos and band logos? I see these packs in your images repo screenshot, thanks!!!

**Comment by kbuffington** [comment]
Fixed in v1.1.1. Codec Logos and Band Logos Color aren't used by this theme, so don't worry about them :)
