### ISSUE TITLE
Runtime error after install and config with JScript Panel v2.2.2.2

### ISSUE THREAD

**Issue by PMJeffery** [kbuffington/Georgia#15]
```
JScript Panel v2.2.2.2 (Georgia by Mordred)
JavaScript runtime error:
Unable to get property '0' of undefined or null reference
File: C:\Users\Splunk\AppData\Roaming\foobar2000\js\georgia-main.js
Line: 2968, Col: 2
```

Running Foobar 1.4.6, CUI v1.2.0b (gowngraded to 1.1.0 as well).
I also edited the georgia.txt to have full paths to the files.  

I checked previous Issues and to use 2.1.7.1, but the link 404's.

I replied back to a comment on your r/foobar reddit thread :)

**Comment by kbuffington** [comment]
That's weird. Struggling to see how that line could be erroring out. Have you installed the fonts? What version of Windows are you on?

You said on reddit you were doing a portable install. Can you zip up the entire foobar folder and send it to me?

**Comment by PMJeffery** [comment]
Thank you for looking into this!!

I removed the images folder since it was like 100MB+ of files you don't need 

[foobar2000.zip](https://github.com/kbuffington/Georgia/files/3512613/foobar2000.zip)

**Comment by kbuffington** [comment]
So I couldn't reproduce the issue with what you gave me, but your portable install wasn't complete. Can you pack up everything except the images folder... including the foobar.exe and miscellaneous stuff? To get yours to work I had to install it over another portable install and I'm not sure if it changed or added something that was missing.

**Comment by kbuffington** [comment]
Didn't get any further information and no one else is reporting this. Feel free to reopen if this is still an issue.
