### ISSUE TITLE
JScript error?

### ISSUE THREAD

**Issue by ggrittz** [kbuffington/Georgia#18]
I can't see to make this work ):

Error: JScript Panel v2.3.0 (Georgia by Mordred)
JavaScript runtime error:
Invalid procedure call or argument
File: C:\Users\ggrit\AppData\Roaming\foobar2000\georgia\js\CaTRoX_QWR\Panel_Playlist.js
Line: 2821, Col: 9
<source text only available at compile time>

Any ideas?

**Comment by KatyLB** [comment]
Not the developer, so I might be wrong, but the Georgia documentation say it's tested up to JScript 2.2.2.2, but your error is with 2.3.0. That could be the problem?

**Comment by ggrittz** [comment]
Oh. I really didn't see that. I'll test with 2.2.2.2, thanks.

**Comment by ggrittz** [comment]
Hey @KatyLB. I installed jscript 2.1.8 and it worked. Thank you. I'm going to close the topic.

**Comment by kbuffington** [comment]
Looks like there might have been in change when 2.3.0 got out of beta. I'll take a look and see, but for now, consider 2.3.0 not officially supported.
