### ISSUE TITLE
Some non-English characters render in a bolder font

### ISSUE THREAD

**Issue by KatyLB** [kbuffington/Georgia#19]
I'm sure you aware of this one, but I wanted to make a report in case there's any sort of possible fix.

Sometimes, foreign characters render in a slightly bolder form. It happens, for example, with the **ź** in Łódź (but not the Ł, curiously), the **ō** in Kayō and the **ą** in benzyną. See below:

![image](https://user-images.githubusercontent.com/37089178/66130083-0c6b2580-e5e9-11e9-80cb-4016fdd92a25.png)

![image](https://user-images.githubusercontent.com/37089178/66130139-23117c80-e5e9-11e9-9b85-fcc5dd25f576.png)

![image](https://user-images.githubusercontent.com/37089178/66130308-6bc93580-e5e9-11e9-8e8a-06c08b96dbaf.png)

I'm guessing this issue is caused by the font not having these characters, but I don't know if there's some sort of fix, or extended version of the font to add, or any other solution?

**Comment by kbuffington** [comment]
D'oh! I was using the Std version of the fonts, and not Pro which has more than just western character sets so Windows was falling back to Arial or something else. I'll update in the next release.

**Comment by kbuffington** [comment]
Update to the latest release and install the new fonts from the fonts folder and things should look consistently good across the UI with both standard English and International text.
