### ISSUE TITLE
Weird crash issue when filtering

### ISSUE THREAD

**Issue by owetre18** [kbuffington/Georgia#2]
I'm not sure why this happens, but whenever I try to filter for certain artists or albums, Georgia crashes.

It happens specifically with the album The Iron Soul of Nothing by Sunn 0))) Meets Nurse With Wound.

It happened a few more times, but I didn't note down what artists and albums.

I also ran into a crash when trying to show albums that are currently being added to the folders that foobar2000 is scanning. So if I'm using beets or something to add my tracks one by one, and I go to the artist that it's currently adding files to, it crashes. I had this problem specifically with The Dear Hunter's Color Spectrum album.

If you need the files that are causing the crash, I can PM them to you or something.

**Comment by kbuffington** [comment]
Is the crash on line 4535 of Panel_Playlist.js?

**Comment by owetre18** [comment]
Yup. Line 4535, col 13.

**Comment by kbuffington** [comment]
Replace line 4534 with this:
    
`var pattern = '^' + _.tf('%album artist%', metadb).replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&") + ' ';`

**Comment by owetre18** [comment]
Works! Thanks!

**Comment by kbuffington** [comment]
Fixed in v0.9.9
