### ISSUE TITLE
Library Tree: compatibility fixes for JSPv2.3.0+

### ISSUE THREAD

**Issue by Wil-B** [kbuffington/Georgia#24]
Here is a version of library tree with compatibility fixes for JSPv2.3.0+. It also has a few other optimisations and fixes.

[Library Tree 1.4.0.4 beta1.txt](https://github.com/kbuffington/Georgia/files/3793439/Library.Tree.1.4.0.4.beta1.txt)

You can do a diff (or document compare etc) between 1.4.0.2 & 1.4.0.4 beta1 to easily identify the changes.

Main changes are:
CHG: View by folder structure now uses faster GetLibraryRelativePaths(), instead of defunct GetLibraryRelativePath. It effects both library initialisation and the library update methods. There are also some bug fixes in there and reworking of the library update code that effect all views. Likely you can just copy & paste the new functions.
CHG: Removed the 500,000 limit in sending tracks to playlist (push.apply  to concat in various places).
CHG: Some optimisation of sorting (lines 431 & 491).
FIX: Tree lines. Now should always join properly at junctions at all dpi setttings (search for l_w, l_wc, l_wf); but I think you already made some high dpi adjustments.
CHG: Themes: switched to GetColourSchemeJSON, due to removal of GetColourScheme (but I think you removed that for Georgia).
CHG: Added workaround for changed behaviour of fb.GetFocusItem() in JSPv2.2.2.1+ (lines 223-225; 1722-1724; effects blur & cover background image drawing: but I think you removed that for Georgia).
CHG: Other minor JSP compatibility changes.

Line numbers are as in 1.4.04 beta1

HTH

**Comment by kbuffington** [comment]
Thanks @Wil-B ! I'll give it a look.

**Comment by kbuffington** [comment]
Integrated your changes and my changes. Need to test a bit more before making an official release but everything seems to be working correctly.
