### ISSUE TITLE
Suggestion for Instructions

### ISSUE THREAD

**Issue by Zeonymous** [kbuffington/Georgia#25]
I'm super casual on this kind of thing (Not even coding, just installing)

So, the roadblock I ran into was on step 8. I didn't understand how to add the Jscript Pannel, specifically as I'm ultra new to Foobar.

Luckily your video helped me out there, through some reddit skimming, and happening to run across it on youtube.

It may seem super trivial, but a little bit of a more direct explanation on adding a Jscript Pannel more specifically targeted at someone who had just downloaded Fubar for the first time (Like myself) could prove helpful in progressing through the install process.

Simple suggestion would be View>Layout>New Scratchbox, ect.. added to the instruction flow.

Awesome configuration, and beautiful design. Keep up the amazing work!

**Comment by jult** [comment]
I would have to agree, it's strange how the mere switching to a (free) theme requires at least an hour's work if you've never used foobar2000 before. Sad, really. I'm used to winamp, where all that was needed was opening a file. I'm afraid foobar has become too complex a mediaplayer, I'll move on to something else.

**Comment by kbuffington** [comment]
@jult Foobar isn't the simplest media player to use, and there's a learning curve regardless. My theme is one of the more complex to setup because I want users to have options and not be forced to just do things the way *I* think they need to be done. If you've watched the video, it's fairly straightforward, but I'll be working on making it even easier when I get some more time.

Edit: Removed outdated video

**Comment by jult** [comment]
Thanks, maybe some day I'll try foobar2k again. I usually like to have those options, but not enough free hours these days. For now, I'm going to be using AIMP. [It has amazing slick skins](http://www.aimp.ru/?do=catalog&os=windows&id=0&sort=1&F2=9).

**Comment by kbuffington** [comment]
Documentation has been completely done from the ground up, and new installation video has been created:

https://kbuffington.github.io/Georgia/
