### ISSUE TITLE
Changing the displayed tags

### ISSUE THREAD

**Issue by mariush2** [kbuffington/Georgia#26]
Hi,

Sorry if this has been asked before, but is it possible to change the displayed tags on the current playing song?

![image](https://user-images.githubusercontent.com/24507952/74597157-5f0a2300-505a-11ea-99e4-577f1fb47077.png)

What I want is to change for example "Last Played" to the song's bitrate. Is this possible?

**Comment by kbuffington** [comment]
I've got "create documentation wiki" on my TODO list, which will explain this better.

For now, you can change the displayed fields by editing globals.js and updating the values in tf.grid. Just add a new label/value pair to the array of JSON and it'll show up when the value doesn't  equate to an empty string.

I should also pull that grid out to it's own file at least, so it'll be easier for people to find and edit.

**Comment by mariush2** [comment]
Thanks. Was able to add the bit rate field like I wanted. What would be really cool is if it were possible to add/edit fields in the UI. 

I saw that there already are some properties for the tags, how hard would it be it take the tf.grid and make it dynamic? (Would gladly be willing to help out in making that feature if you think it's doable)

**Comment by kbuffington** [comment]
Configuration files are being added which include full customization of the metadata grid, and all title formatting strings used throughout the UI.

**Comment by kbuffington** [comment]
This is now configurable in the latest betas and will be in the 2.0 release coming shortly.
