### ISSUE TITLE
Text rendering bug when displaying album titles or artist names

### ISSUE THREAD

**Issue by magnificar** [kbuffington/Georgia#28]
Whenever the character Á is put on an album title or an artist name, it gets smushed with the following character. Like this:
![2020-02-24 (4)](https://user-images.githubusercontent.com/61425748/75176172-6db7a080-5712-11ea-8cef-a76a4a2283fe.png)
From what I've tested this doesn't appear on any other field, or with similar characters like á, É, etc

**Comment by kbuffington** [comment]
Verified, with my my own copy of that album:
![image](https://user-images.githubusercontent.com/2282004/75179541-e8c38b80-56ff-11ea-9c13-b6e0e2c5bf48.png)

Interestingly, it's only on the **antialiasBold** font. They're all from the same font family, so it's very confusing. I'll see if I can't find an alternate, or updated copy that fixes this issue.

**Comment by kbuffington** [comment]
Fixed in 1.1.7.

I couldn't find a font that looked as good as what I was currently using unfortunately. Tried out a bunch of options and they all kinda sucked, so I did the stupidest thing possible and just check to see if Á is in the title, and use a different font just for those strings.
