### ISSUE TITLE
No country flags or record logos appear

### ISSUE THREAD

**Issue by klercke** [kbuffington/Georgia#29]
No matter what song I play, I can't get country flags or record label logos to appear. There's a very good chance I'm doing something wrong here as I'm new to foobar.

**Comment by kbuffington** [comment]
To get images for country flags and record labels to appear you need:

- To have the image packs installed correctly
- To have your files properly tagged. Default values for flags is %artistcountry% and for record labels it's either %publisher% or %label%. These are of course configurable if you're using another tag already.
- For artist country you also need to have the full country name. It does not currently work with 2 or 3 character abbreviation, although I'm considering adding that.
