### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by ghost** [kbuffington/Georgia#3]
I noticed that the seekbar refreshed a lot in a second. It looks awesome but will cause high CPU usage( the 'on_paint' function will be executed every time....)

I believe the strategy used by thanhdat1710 in https://www.deviantart.com/thanhdat1710/art/Album-Library-Search-WSH-Script-396270784 is quite good that he separated the panel into two and repaint them respectively(say if only the inputbox area be refreshed, code lines of the album list (in on_paint function) would not be executed)

**Comment by kbuffington** [comment]
Yup, it's possible. There's a few things to be aware of. The frequency of progress bar updates is proportional to the width of the progress bar, and the length of the song. The wider foobar is, and the shorter a song is the more frequent the progress bar will need to be updated. With the playlist hidden, on a 4K monitor, and with a 4 minute long song, my CPU is at 4-5% which I'm very happy with. With a 30 second long song on the same monitor and playlist visible, my CPU bounces between 20-30% which is pretty high. Fortunately that's only for the 30 seconds of the song.

Now if you have an older computer, CPU might be higher than you'd like. There's a setting in the options menu which you can uncheck to disable more frequent progress bar updates. Then it should only redraw every 250 or 500ms. I can't remember.

The problem with separating it into a different panel is that the dynamic theme requires loading and processing the album art, and I think there might be issues trying to read the artwork at the same time from multiple panels. I also don't think it'd look as good. 

However, if CPU is still an issue you can disable the progress bar from the options menu, and use your own in another panel (foo_wave_seekbar is a good one to use). This should stop the frequent `on_paint`s.

I'll take a look and see if I can't speed up drawing when the playlist is visible though.

**Comment by ghost** [comment]
Thanks for reply.

'separate into 2' does not mean it need another js-panel. There's only ONE js-panel the same with the current theme. You may refer to the script (URL I pasted before) coded by thanhdat1710 (I found it difficult for me to describe it clearly in Eng)

**Comment by kbuffington** [comment]
I'll take a look and see if it's doing something different. Currently, when the progress bar refreshes, it only redraws the area of the progress bar and the time. It does go through the rest of the draw code, but it essentially takes zero time because every other draw command is clipped out.
