### ISSUE TITLE
Possible to show lyrics?

### ISSUE THREAD

**Issue by Kuuhhl** [kbuffington/Georgia#30]
I wondered how I can show the lyrics of the song (.lrc file). 
The .lrc-files get detected fine with the LyricShowPanel-Component, but they don't get displayed in the theme. 
What can I do to get the lyrics to display?

**Comment by kbuffington** [comment]
Are you downloading the .lrc files?

It should look for them in the current folder, and in your foobar profile path + `/lyrics`. If your lyrics aren't in either of those locations, you can add it to the `tf.lyr_path` array in globals.js (line 165).

It also expects your lyrics files to either be "Artist - Title.lrc" or "Artist -Title.lrc".

If you have a folder path that you think might be pretty common, or an artist/title file format that you think should be standard, I can add it to the theme and then everybody would benefit.

**Comment by Kuuhhl** [comment]
Thanks for the answer. 

My lyrics are in formatted like this: `tracknumber + ' - ' + title`  (e.g. `18 - The Incredible True Story.lrc`)
And sometimes like this: `tracknumber + ' - ' + artist + ' - ' + title`  (e.g. `08 - Logic - The Incredible True Story.lrc`)

Based on your answer I edited the array in globals.js like the following:
```
tf.lyr_filename = [ // filenames to look for lyrics files. Both .lrc and .txt will be searched for each entry in this list
	tf.lyr_artist + ' - ' + tf.lyr_title,
	tf.lyr_artist + ' -' + tf.lyr_title,
	tf.tracknum + ' - ' + tf.lyr_title,
	tf.tracknum + ' - ' + tf.lyr_artist + ' - ' + tf.lyr_title,
];
```
The .lrc files still don't get recognized this way. The only way I managed to add my lyrics is by adding the specific file name like this:
```
tf.lyr_filename = [ // filenames to look for lyrics files. Both .lrc and .txt will be searched for each entry in this list
	'18 - The Incredible True Story'
];
```
The .lrc files were automatically downloaded from Deezer along with the songs using Deezloader with the default naming settings.

**Comment by kbuffington** [comment]
Aha! That's because tf.tracknum is actually formatted like `"01."`. For your case add:

```
tf.tracknum.replace('.','') + ' - ' + tf.lyr_title,
tf.tracknum.replace('.','') + ' - ' + tf.lyr_artist + ' - ' + tf.lyr_title,
```

I'll add it as a new default to the next version.

**Comment by Kuuhhl** [comment]
Thanks! It works now.

**Comment by Zephyr0ck** [comment]
Hi, i've saved my lyrics on another Drive, How to use another location for Georgia Theme?
what line and what code should i use?
