### ISSUE TITLE
Release year appear as 0000 in playlist view after latest update

### ISSUE THREAD

**Issue by magnificar** [kbuffington/Georgia#32]
It's a problem specific for the last update (1.1.8-beta2), it was working fine with 1.1.7. It happens only in the playlist view and if the tag is formatted like year-month-date, or year-month. If the tag is just the year, it works fine.
![2020-05-04 (4)](https://user-images.githubusercontent.com/61425748/81031038-46dbc000-8e61-11ea-92fd-39069ab8bcc9.png)
![2020-05-04 (8)](https://user-images.githubusercontent.com/61425748/81031063-5955f980-8e61-11ea-856f-a8173c95acd3.png)
![2020-05-04 (2)](https://user-images.githubusercontent.com/61425748/81031122-97ebb400-8e61-11ea-9e97-c8b1d9c696ad.png)

**Comment by kbuffington** [comment]
Crap.

Can you right click on the panel, bring up the properties page and then delete the following two keys:
"Tag Fields: Year" and "Tag Fields: Date". Hit okay, and then tell me if dates look correct again.

**Comment by magnificar** [comment]
I deleted these and now it's working fine. Don't really understand how this worked out, but thank you!

**Comment by kbuffington** [comment]
I changed the values of those fields so they'd work better with improved playlist code which utilizes them, but you still had the old defaults because I forgot to clear them on theme upgrade. I'll leave this ticket open until I push the code to reset them.

**Comment by kbuffington** [comment]
Should be fixed by default in 1.1.8
