### ISSUE TITLE
Screenshot(s), maybe?

### ISSUE THREAD

**Issue by 0xotHik** [kbuffington/Georgia#33]
It's not an issue  in the truest sense of the word, but I think some screenshots would be nice, and may motivate some people to give the theme a try :)

**Comment by kbuffington** [comment]
Lack of proper documentation is a huge issue right now. That's my work for post 1.1.8, including lots of fancy screenshots :)

**Comment by VonTittyslappen** [comment]
I had to do a fair bit of digging and found an imgur album for it on the hydrogenaudio thread:-

https://imgur.com/a/TtjUS
