### ISSUE TITLE
Lyrics display bug

### ISSUE THREAD

**Issue by Kuuhhl** [kbuffington/Georgia#35]
When the lyrics player shows the first line of a verse, it doesn't get marked yellow like all the other lines. 

![demonstration-georgia](https://user-images.githubusercontent.com/50250716/81497397-87529800-92be-11ea-87ab-362b500cf4ca.gif)

**Comment by kbuffington** [comment]
Can you send me the .lrc file? Want to verify it's not doing anything weird.

**Comment by Kuuhhl** [comment]
https://workupload.com/file/8xDS5qLsXcj

**Comment by kbuffington** [comment]
So the issue is the .lrc file. Whoever created it added blank lines between each paragraph with the same timestamp as the next line:
```
[01:05.55]I don't give a fuck, God sent me to piss the world off!
[01:08.43]
[01:08.43]Hi! My name is (what?)
[01:10.19]My name is (who?)
[01:11.56]My name is
[01:12.77]Slim Shady
[01:13.86]Hi! My name is (huh?)
[01:15.71]My name is (what?)
[01:17.20]My name is
[01:18.42]Slim Shady
[01:19.46]
[01:19.46]Hi! My name is (what?)
[01:21.42]My name is (who?)
[01:22.78]My name is
[01:23.99]Slim Shady
```

That's confusing the lyrics renderer. Normally you'd use a blank like that when the previous line has ended, but before the next line has started. I'll see if there's something I can do to handle this weird case, but no promises.

**Comment by Zephyr0ck** [comment]
> When the lyrics player shows the first line of a verse, it doesn't get marked yellow like all the other lines.
> 
> ![demonstration-georgia](https://user-images.githubusercontent.com/50250716/81497397-87529800-92be-11ea-87ab-362b500cf4ca.gif)

How to make lyrics work with Georgia? i've all my lyrics (.lrc) saved into a folder under (G) drive but doesn't display on Georgia :(

**Comment by Kuuhhl** [comment]
The lyrics should be in the same folder the music is in.
Also they should follow the naming conventions of Georgia. To see them, just look at [this](https://github.com/kbuffington/Georgia/issues/30) thread.

> > When the lyrics player shows the first line of a verse, it doesn't get marked yellow like all the other lines.
> > ![demonstration-georgia](https://user-images.githubusercontent.com/50250716/81497397-87529800-92be-11ea-87ab-362b500cf4ca.gif)
> 
> How to make lyrics work with Georgia? i've all my lyrics (.lrc) saved into a folder under (G) drive but doesn't display on Georgia :(

**Comment by Zephyr0ck** [comment]
> The lyrics should be in the same folder the music is in.
> Also they should follow the naming conventions of Georgia. To see them, just look at [this](https://github.com/kbuffington/Georgia/issues/30) thread.
> 
> > > When the lyrics player shows the first line of a verse, it doesn't get marked yellow like all the other lines.
> > > ![demonstration-georgia](https://user-images.githubusercontent.com/50250716/81497397-87529800-92be-11ea-87ab-362b500cf4ca.gif)
> > 
> > 
> > How to make lyrics work with Georgia? i've all my lyrics (.lrc) saved into a folder under (G) drive but doesn't display on Georgia :(

Thanks mate! i'll do :)

**Comment by kbuffington** [comment]
Verified that this issue has been fixed.
