### ISSUE TITLE
Volume control missing from 1.8 stable

### ISSUE THREAD

**Issue by Artins90** [kbuffington/Georgia#36]
After updating to the stable 1.8 stable release, I noticed that the volume control is now missing.
It was there in 1.1.8-beta2.

<img width="1915" alt="Capture" src="https://user-images.githubusercontent.com/28777957/81544648-166fb680-9378-11ea-81a8-a2c0c79ef44a.PNG">

Jscript panel shows:
// @import "%fb2k_profile_path%georgia\js\volume.js"

The file is present inside the js folder.

**Comment by kbuffington** [comment]
You have to re-check the "Show Volume Control" inside the Options >> Transport Controls.

Unfortunately I had to reset all the Transport settings with the final release.

**Comment by Artins90** [comment]
I should have checked, thank you it works.

**Comment by kbuffington** [comment]
I should have added a mention to the release notes. Doing that now.
