### ISSUE TITLE
Error added album

### ISSUE THREAD

**Issue by dom63100** [kbuffington/Georgia#38]
hi,
I have an indication error for the date of the album selected for playback. And that's true for all albums!
![SharedScreenshot](https://user-images.githubusercontent.com/65892485/82794692-31135680-9e73-11ea-8067-3a0311e09d1b.jpg)

**Comment by kbuffington** [comment]
Do you have foo_playcount installed?

I'm assuming foo_playcount is not installed, and therefore the %added% timestamp is 0 which on windows is 12:00AM on 01/01/1601. What does the foobar properties dialog show for the value 
of added?

**Comment by dom63100** [comment]
Hi,
What a mistake, this component was not installed! Now, it's OK.
Thank's
