### ISSUE TITLE
Oi!

### ISSUE THREAD

**Issue by ghost** [kbuffington/Georgia#4]
Since your theme contains the Catrox playlist... I'm going to comment here. I noticed your post in the Catrox thread on HA saying JScript Panel couldn't write tags to files - it can!! 

Even WSH panel mod has basic functionality but I completely rewrote it in v1.3 and it's documented here.

https://github.com/marc2k3/foo_jscript_panel/wiki/Breaking-Changes#v130

The handle list section in the docs also contains a link to this info.

**Comment by kbuffington** [comment]
Ha! Well I'm dumb. Don't know how I ever missed that. I don't really have a need for it right now, but that's good to know.

**Comment by ghost** [comment]
No worries.
