### ISSUE TITLE
Playlist - Too many tags, or size causes tags to lack rendering space

### ISSUE THREAD

**Issue by voc0der** [kbuffington/Georgia#41]
When using a larger font (neccessary for me to even see it), and actually even with a smaller font, sometimes a cd has enough tags to do the following:
![image](https://user-images.githubusercontent.com/23507129/84263094-d9205500-aaec-11ea-90d9-865e50da71c9.png)

I realize that in most cases having the vanilla font size probably doesn't have this issue; but I'm wondering what the best solution would be for people with this setup? Maybe to count the length of the compiled label string, and if it's above that allotted space estimate (I've seen this in the code in other places) or maybe even just a preference size max? then start trimming labels (e.g. only showing 3) until it fits or something?

The labels proceed | flac | n track | y time and finally on the right; aligned is the record label itself, so if there are too many rendered labels those 2 entities run out of horizontal space to draw on.

For reference, my display where it occurs is a 22" 1920x1080 display. Thanks again for making this awesome theme, and I'm willing to help come up with a fix if you want.

**Comment by kbuffington** [comment]
I'm adding an item to my todo list to get this fixed.

**Comment by kbuffington** [comment]
Fixed in 1.1.9. There were lots of issues related to font sizes in the group info line that I've since fixed. Should look great regardless of font size or 4k mode.
