### ISSUE TITLE
Date with .CUE

### ISSUE THREAD

**Issue by Zephyr0ck** [kbuffington/Georgia#42]
Georgia theme is insane! It's my first time using and really love it.
 i've one question, i'm using .cue + flac but for date i'm getting this: 0000

on .CUE:

REM DATE 1991 / 2009 
![2020-06-13_18-03-33](https://user-images.githubusercontent.com/66889502/84580819-43aceb80-ada0-11ea-9548-9be39f9f7edb.png)
![2020-06-13_18-02-55](https://user-images.githubusercontent.com/66889502/84580820-44de1880-ada0-11ea-989d-f23e0543f595.png)

**Comment by kbuffington** [comment]
I need to hide the date if no date was found in the metadata. Probably isn't cue sheet related. It's on my todo list.

**Comment by kbuffington** [comment]
This should be fixed in 1.1.9. Please reopen if you still encounter the issue after updating.
