### ISSUE TITLE
%vinyl side% and %vinyl tracknumber% wont display record unless song restart

### ISSUE THREAD

**Issue by lilZoey** [kbuffington/Georgia#45]
%vinyl side% and %vinyl tracknumber% wont display the record unless I stop the song, and play the song again, when the song finishes the next one wont show the record unless I stop and play again.

I believe I have the meta data set up correctly.
![image](https://user-images.githubusercontent.com/59385832/87879414-43f86200-c9b0-11ea-9114-64b3320af0ab.png)

**Comment by kbuffington** [comment]
So you're saying that those properties are set before the song starts, but they don't show up unless you restart the song?

**Comment by lilZoey** [comment]
So I have vinylA, & vinylB In album folder. and have the properties listed above. 
When the album plays the vinyl does not show up next to the album image. When I stop or pause the song, then play it again the vinyl will show for that song, displaying the correct vinylA or vinylB depending which vinyl side the song is on. But when the song ends and the next song in the album begins it will not show the either Vinyls until I stop/pause and play the song again, then the correct vinyl will show again.

The only way I could find to fix this is instead of using vinylA and vinylB, just name the png cd1 and cd2. simply switching the file name will fix the issue.

**Comment by kbuffington** [comment]
I can't reproduce this, but I've got an idea of what's wrong... and it's that I'm an idiot.

Go to line 1436 of georgia-main.js, where `lastVinylSide` is assigned. Replace that entire line with the one below.

```
	lastVinylSide = $('$if2(' + tf.vinyl_side + ',ZZ)');
```

Let me know if that solves the problem.

**Comment by lilZoey** [comment]
This did not solve the problem, although now instead of refusing the load the vinyl image unless the song is stopped and started it will sometimes load the vinyl when the album image changes to show the back side of the album. and will randomly decide to load the vinyl at the start of the song.

**Comment by kbuffington** [comment]
Damn, thought I had it. Tried a couple more things and still can't reproduce on my end, so I'll need your help debugging. Before line 1369 in georgia-mains.js add this line:

```
	console.log('IMAGE_DBG!:', pref.aa_glob, aa_list.length, current_path, last_path, albumart, $('$if2(%discnumber%,0)'), lastDiscNumber, $('$if2(' + tf.vinyl_side + ',ZZ)'), lastVinylSide);
```

Then reload the theme, open up your foobar console, play a song, and copy me the line or screenshot the console where "**IMAGE_DBG!:**" is visible.

Also, do you have more than 10 pieces of artwork (including cd/vinyl.pngs) in this folder?

**Comment by lilZoey** [comment]
I played a few different songs from the album thats not showing the vinyls correctly, these where the "IMAGE_DBG!:" results,

After restarting foobar and playing first song (vinyl did load as it would stopping and starting the song):
`IMAGE_DBG!: True 0 The Keyblade War  1  A `

Tracking forward a song (No vinyl loading)
`IMAGE_DBG!: True 2 The Keyblade War The Keyblade War 1 1 A A`

Stopping the track and starting it again (vinyl loaded as it normally does with a stop and start)
`IMAGE_DBG!: True 2 The Keyblade War  1 0 A A`

> Also, do you have more than 10 pieces of artwork (including cd/vinyl.pngs) in this folder?

No, I'll supply an image of the album folder in question.
![image](https://user-images.githubusercontent.com/59385832/87999607-fc153000-cac0-11ea-8787-899d679deb5a.png)

**Comment by kbuffington** [comment]
Okay, I was finally able to reproduce... and this is a weird fucking bug. It's being tripped up because your vinyl art is loaded before the front art, and therefore when the size of the cdArt is calculated, it's the exact same size as the front cover, which trips a check that's supposed to ensure the cdart doesn't appear weirdly sized around the cover... and so it never draws. A number of other conditions also need to be just right... etc. Here's the fix:

- Revert all the changes you made to georgia-main.js.
- Replace line 2446 with this: `cdart_size.w = Math.floor(cdart.Width * album_scale) - 4; // width`
- Replace line 2447 with this: `cdart_size.h = cdart_size.w; // height`
- Replace line 2454 with this: `cdart_size.y = geo.top_art_spacing + 2; // top`
- Reload and everything should be good

Unfortunately I'm knee deep into a rewrite of Georgia using foo_spider_monkey and I can't fix this in the real codebase for now.

**Comment by lilZoey** [comment]
Ah this fixed the issues! Thanks a bunch. 
Cant wait to see what the rewrite has in store, georgia is deferentially the best theme I've used. makes foobar feel like a real media product.

**Comment by kbuffington** [comment]
Thanks for reporting the issue and being patient with the debugging!
