### ISSUE TITLE
Transport button icons display improperly

### ISSUE THREAD

**Issue by pw-z** [kbuffington/Georgia#47]
The icons display improperly like this:
 
![image](https://user-images.githubusercontent.com/35032653/90513368-1c084400-e192-11ea-85d4-5e36dee91149.png)

Everything was just fine yesterday and I did nothing to my computer besides a system upgrade. (Windows 10 2004  ->  Windows 10 20H2) What could be the cause of this problem?

**Comment by kbuffington** [comment]
You need to install the fonts in the fonts folder again.

For future reference if you're having issues, and things don't look right, the first thing to do is check that things are installed correctly under Help => Georgia Theme Status.

**Comment by pw-z** [comment]
😱Oops, I was so stupid that I didn't think it was the font. Now it works well. Thanks a lot.
