### ISSUE TITLE
Crashing when cycling through art

### ISSUE THREAD

**Issue by magnificar** [kbuffington/Georgia#49]
If there is 10 or more image files and a cd.png is loaded, Georgia will crash while going from image no.9 to image no. 10. 
This is the error message: 
![2020-09-26 (2)](https://user-images.githubusercontent.com/61425748/94336851-96f82200-ffbc-11ea-9b54-15475ecfcef1.png)
(that means Javascript runtime error in Portuguese)

**Comment by kbuffington** [comment]
Not sure what caused this, but I verified it no longer happens.
