### ISSUE TITLE
Crash when creating a new playlist

### ISSUE THREAD

**Issue by alxbnv** [kbuffington/Georgia#5]
Selecting playlists > Create New Playlist seems to cause a crash with an error:

```
Error: JScript Panel v2.1.7.1 (Georgia by Mordred)
JavaScript runtime error:
Invalid procedure call or argument
File: ........\foobar2000\georgia\js\CaTRoX_QWR\Control_Button.js
Line: 309, Col: 4
<source text only available at compile time>
```

**Comment by kbuffington** [comment]
I can't reproduce. Are you creating the playlist using the playlists menu, or by clicking on the bar at the top of the Playlists Panel?

If it's from the menu, can you replace line 309 with this:
`lists.AppendMenuItem(MF_STRING, playlistId + i, plman.GetPlaylistName(i).replace(/\&/g, '&&') + ' [' + plman.PlaylistItemCount(i) + ']' + (plman.IsAutoPlaylist(i) ? ' (Auto)' : '') + (i === plman.PlayingPlaylist ? ' (Now Playing)' : ''));`

and tell me if the problem goes away?

**Comment by alxbnv** [comment]
Creating the playlist [by using this option ](https://imgur.com/fNPtjp4) was causing the issue. But replacing the 309 line with the code that you've provided fixed it!

**Comment by kbuffington** [comment]
Great! You've helped me discover some issues when there are no playlists (clearly not a state Georgia handles well at the moment). They'll make it into the next release. Thanks!

**Comment by InFluxxYT** [comment]
This also causes an error in Panel_Playlist.js (Line: 5919) when trying to use the upper right-hand button to view the playlist, not sure if that's one of the issues you discovered yourself.
