### ISSUE TITLE
Only one logo gets displayed at the same time/ album artist gets prefered over regular artist

### ISSUE THREAD

**Issue by mist475** [kbuffington/Georgia#51]
Currently the logo of the album artist gets prefered over the song artist, even if the album artist is various artists, i don't know if this is intended behaviour. Also only one logo gets displayed at the same time.

**Comment by mist475** [comment]
fixed in the new beta, still only one artist gets displayed. even if there are multiple album artists

**Comment by kbuffington** [comment]
It's a little more complicated to show multiple logos. I'll add that as a TODO and check to make sure it looks good before implementing. Closing this issue for now.
