### ISSUE TITLE
Album art doesn't refresh with foo_youtube and foo_spotify (probaply streaming related)

### ISSUE THREAD

**Issue by mist475** [kbuffington/Georgia#53]
When skipping songs everything works just fine, when you let songs just play the album artwork doesn't update. Refreshing the theme temporarily fixes it until the next songs starts. See example:
![georgiaissue](https://user-images.githubusercontent.com/70655895/96872075-6c8e6d00-1473-11eb-9330-0a22f127c9cc.png)

**Comment by kbuffington** [comment]
Should be fixed in the 2.0.0-beta1 release. If you could test it out, I'd appreciate it.

**Comment by mist475** [comment]
Just tested it, it works now, thanks
