### ISSUE TITLE
Date+Year field in ID3 tags causing calcAgeDateString function to fail

### ISSUE THREAD

**Issue by michaelholt1995** [kbuffington/Georgia#55]
Hello!

Absolutely loving Georgia and don't think I'll be able to go back to stock Foobar now.

However, I seem to be struggling with certain tracks.

Taking you through my investigation for a min...

### Symptom: 
I'll go to play a track and Georgia will crash (but the track continues to play and stock Foobar works fine) with this error.

```
JScript Panel v2.4.1.1 (Georgia by Mordred)
JavaScript runtime error:
'fail' is undefined
File: C:\Users\Michael\AppData\Roaming\foobar2000\georgia\js\helpers.js
Line: 237, Col: 4
```
Digging in a bit, it looks like it's having an issue with the calcAgeDateString(date) function.

Examples of tags against songs that work
![image](https://user-images.githubusercontent.com/39269367/101827305-0c897e00-3b28-11eb-8cda-79b229fd4e04.png)
![image](https://user-images.githubusercontent.com/39269367/101829053-51161900-3b2a-11eb-898a-26e6cea37b09.png)

Examples of tags on songs that don't
![image](https://user-images.githubusercontent.com/39269367/101826467-f3cc9880-3b26-11eb-84f8-4e9247139206.png)
![image](https://user-images.githubusercontent.com/39269367/101827365-24610200-3b28-11eb-978e-104630f1cd1d.png)

Looking at them side by side like this, it looks like it could be the Date (DDMM) field causing an issue? Possibly conflicting with the parameter as part of the calcAgeDateString function.

However, then using Cyndi Lauper's 1983 non-working classic to experiment with and understand workarounds:

Tag set that doesn't work
![image](https://user-images.githubusercontent.com/39269367/101828557-a0a81500-3b29-11eb-966d-e9ec6ca5c3a5.png)

Removing just the Year field (so it looks like this) works
![image](https://user-images.githubusercontent.com/39269367/101827913-cb459e00-3b28-11eb-8095-518f2e8d0892.png)

Removing just the Date field (so it looks like this) also works.
![image](https://user-images.githubusercontent.com/39269367/101828961-2e840000-3b2a-11eb-80a5-c54ae95ac542.png)

So something is getting very upset about the combination of Year **and** Date fields being present.

I have no issue with just removing the Date field from my files but would rather see if the root cause can be solved before going ahead and doing that.

Let me know if you need any more info from me :) 

Thanks,
Michael

**Comment by michaelholt1995** [comment]
Okay, this one working fine has blown my theory out of the water

![image](https://user-images.githubusercontent.com/39269367/101911189-f0cdb880-3bb7-11eb-9489-b4e7dcf85843.png)


![image](https://user-images.githubusercontent.com/39269367/101911226-ffb46b00-3bb7-11eb-91a1-e1d1f623721d.png)

**Comment by kbuffington** [comment]
So the issue is definitely the DATE field. My guess is that the problem is the DDMM, and the theme expects MMDD. So `0310` works because March 10th is a valid date. Find one of your files that doesn't work and adjust the 2nd two digit number in the date field so that it's <12 and see if it works again (i.e. for Cyndy Lauper `1014` => `1011`).

**Comment by michaelholt1995** [comment]
Thanks for the suggestion @kbuffington - can confirm that `1011` works

![image](https://user-images.githubusercontent.com/39269367/101931990-0ea81700-3bd2-11eb-9e40-2977d75c73e7.png)

**Comment by kbuffington** [comment]
Awesome. In the upcoming beta you'll have a lot more control over the titleformatting strings used so we can probably control for this.

**Comment by kbuffington** [comment]
This should be fixable with some titleformatting magic in the latest betas or official release.
