### ISSUE TITLE
How to display full screen?

### ISSUE THREAD

**Issue by EmpressFiona** [kbuffington/Georgia#57]
I guess this isn't really an 'issue' as such, but the instructions say that this is best used full screen...but as far as I can tell, there's no way to actually use it full-screen (ie, without title bar and over the task bar). Is there something in the instructions I'm missing, some component or context option I don't know about, or is 'full screen' best read as 'maximized'?

**Comment by kbuffington** [comment]
There's no true-full screen mode. I just meant maximizing the window. If you use Columns UI you can hide the menu bar though which makes things look much better since the menus are basically duplicated.

**Comment by ghost** [comment]
I could've _sworn_ there was an option that disabled the title bar and task bar i.e a full screen option, am I just remembering things wrong?

**Comment by kbuffington** [comment]
There's nothing that this theme can do that will disable the title bar. If you use Columns UI, you can disable the task bar and menu bar. If you use foo_ui_hacks, you can also disable the title bar, but then you won't be able to minimize and maximize the window. I'm working on fixing that now though.
