### ISSUE TITLE
There is a small gap between album-art and the metadata section

### ISSUE THREAD

**Issue by mist475** [kbuffington/Georgia#59]
![georgiaminorissue](https://user-images.githubusercontent.com/70655895/103880973-1e841f80-50da-11eb-9b30-2fbc4c818f3d.png)
see image

**Comment by kbuffington** [comment]
That's a line a draw that is supposed to be slightly darker than the calculated primary theme color. When the algorithm picks a color that is identical to the color on the border of the album, and I don't draw the line, it looks weird when you can't visually determine where the edge of the album ends.
