### ISSUE TITLE
Error in JScript?

### ISSUE THREAD

**Issue by HEHatley** [kbuffington/Georgia#6]
This style is single-handedly what made me go with foobar2000 for my music player, but I can't seem to get the JScript working. I placed everything in the correct folders, but when I try to paste in the code, I fet the following error.
```
Error: JScript Panel v2.1.7.1 (Georgia by Mordred)
JavaScript runtime error:
Invalid procedure call or argument
File: D:\Programs\foobar2000\georgia\js\CaTRoX_QWR\Panel_Playlist.js
Line: 2824, Col: 9
<source text only available at compile time>
```
I'm not sure what I'm doing wrong, and this code is definitely not my strong suit.

**Comment by kbuffington** [comment]
Probably not anything you're doing wrong. That's a strange error, but it's probably specific to your setup, so lets debug.

First, I'm guessing that the theme loads, it just crashes when you try and display the Playlist (or you have the "Show Playlist on Startup" option checked). Can you open up Panel_Playlist.js in a text editor, then find line 2824. Just to make sure we're working from the same starting place, line 2824 currently looks like this, correct?:
`plman.PlayingPlaylist = plman.ActivePlaylist;`

If that's the case, then add this line of code directly before 2824 (it will go inside the `if` statement):
`console.log('>>> Playlist Debugging - ActivePlaylist', plman.ActivePlaylist, 'count:', plman.PlaylistCount);`

Now go back to foobar, in the View menu select "Console" while will bring up the debugging console. Right click and reload my theme, and do whatever you did to make it crash. In the console you should see that looks something like ">>> Playlist Debugging - ActivePlaylist -1 count: 0"

Paste that here and we'll proceed from there.

**Comment by HEHatley** [comment]
Okay, I did that, and in the console I got that message directly above the JScript Error message
```
>>> Playlist Debugging - ActivePlaylist -1 count: 0
Error: JScript Panel v2.1.7.1 (Georgia by Mordred)
JavaScript runtime error:
Invalid procedure call or argument
File: D:\Programs\foobar2000\georgia\js\CaTRoX_QWR\Panel_Playlist.js
Line: 2824, Col: 9
<source text only available at compile time>
```

**Comment by kbuffington** [comment]
Seems to be a change in jscript panel after version v2.1.5.2. I downloaded 2.1.7.1 and now see the same crash.

Change line 2823 to:
`if (plman.PlayingPlaylist === -1 && plman.ActivePlaylist !== -1) {`
and that should fix the problem.

**Comment by HEHatley** [comment]
Perfect, that worked perfectly! Some of the fastest most helpful troubleshooting I've ever received.
