### ISSUE TITLE
Any way to hide "properties panel"?

### ISSUE THREAD

**Issue by JFizDaWiz** [kbuffington/Georgia#60]
Is there any way to completely hide the panel to the left of the album artwork when the Playlist or Library is in view? Currently it just compresses so there is a solid colour bar to the left of the album work (colour depends on album cover colour)
Or is there a way to code a specific colour for that section so it can match the background?

![1](https://user-images.githubusercontent.com/6844314/103961759-2caa5e00-5123-11eb-959c-d5677a9f4099.png)
![2](https://user-images.githubusercontent.com/6844314/103961761-2ddb8b00-5123-11eb-9a29-ac3ce5bd1892.png)

**Comment by kbuffington** [comment]
Currently no, but I'll add a flag for that. Seems like a reasonable request.

**Comment by kbuffington** [comment]
Added to config file in 2.0.0-beta2.

**Comment by JFizDaWiz** [comment]
I really appreciate your hard work, but which is the new setting for this, can't seem to find it.

**Comment by kbuffington** [comment]
Open `georgia-config.jsonc` and set the value of `hidePanelBgWhenCollapsed` to true.

**Comment by JFizDaWiz** [comment]
Thank you! This is now officially my default Foobar theme across all my computers
