### ISSUE TITLE
Flags and Labels images on Georgia v2.0.0-beta1

### ISSUE THREAD

**Issue by Zephyr0ck** [kbuffington/Georgia#61]
I'm using Georgia v2.0.0-beta1 on foobar2000 Portable, everything works good but i've 2 "bugs" or fails for show flag image and label.

Path foobar2000:

C:\Users\j0nz\Desktop\foobar2000\profile\Georgia\
C:\Users\j0nz\Desktop\foobar2000\profile\Georgia\**flags**
C:\Users\j0nz\Desktop\foobar2000\profile\Georgia\**recordlabel**

![Capture](https://user-images.githubusercontent.com/66889502/104501484-6a850780-55a5-11eb-8e8c-d9136c323d11.PNG)

What am I doing wrong?

**Comment by Zephyr0ck** [comment]
Sorry, i've checked and code and edit some code lines to fix it.

georgia-main,js

Flags is working with this:

from this:
`pref.flags_base = fb.ProfilePath + 'images/flags/'; // location of artist country flags`

 to this:
`pref.flags_base = fb.ProfilePath + 'georgia/images/flags/'; // location of artist country flags`

Label is working with this:

from this:
`pref.label_base = fb.ProfilePath + 'images/recordlabel/'; // location of the record label logos for the bottom right corner`

to this:
`pref.label_base = fb.ProfilePath + 'georgia/images/recordlabel/'; // location of the record label logos for the bottom right corner`

all this edited on **georgia-main.js** at line: **191** / **195**

Thanks for this great foobar theme and sorry for the inconvenience

**Comment by kbuffington** [comment]
Not an inconvenience!

Yeah, you're supposed to install them to an `/images` folder created inside the georgia folder 😀  Maybe I'll add the images folders as configurable paths in the georgia-config file though. That'd be useful to people who want to install those somewhere other than the defaults. I'll try and get that done for beta2.

Nice to see you edited the `metadataGrid` values!

**Comment by kbuffington** [comment]
Sorry I just realized I misspoke. The `/images/` folder is supposed to be at the same level as the main Georgia folder, but not inside it. Again, I'll still allow them to be installed elsewhere though.
