### ISSUE TITLE
Crashing on launch: "currentVersion is not defined"

### ISSUE THREAD

**Issue by ghost** [kbuffington/Georgia#63]
Error: Spider Monkey Panel v1.3.1 (Georgia v2.0.0 by Mordred)
include failed:
currentVersion is not defined

File: settings.js
Line: 9, Column: 21

Stack trace:
  @settings.js:9:21
  loadAsyncFile/</<@georgia-theme.js:9:13

Component Report:
Core (2020-09-25 11:48:56 UTC)
    foobar2000 core 1.6.1
foo_abx.dll (2019-03-11 19:32:20 UTC)
    ABX Comparator 2.0.6d
foo_albumlist.dll (2020-09-25 11:48:06 UTC)
    Album List 4.7
foo_cdda.dll (2020-09-25 11:48:02 UTC)
    CD Audio Decoder 1.6.1
foo_converter.dll (2020-09-25 11:48:02 UTC)
    Converter 1.6.1
foo_discord_rich.dll (2020-01-29 10:36:46 UTC)
    Discord Rich Presense 1.2.0
foo_dsp_eq.dll (2020-09-25 11:47:52 UTC)
    Equalizer 1.2.2
foo_dsp_resampler.dll (2019-08-05 20:16:30 UTC)
    SoX Resampler 0.8.7
foo_dsp_std.dll (2020-09-25 11:47:54 UTC)
    Standard DSP Array 1.6.1
foo_dynamic_range.dll (2011-11-12 22:18:34 UTC)
    Dynamic Range Meter 1.1.1
foo_fileops.dll (2020-09-25 11:48:08 UTC)
    File Operations 1.6.1
foo_freedb2.dll (2020-09-25 11:47:56 UTC)
    Online Tagger 0.8
foo_hdcd.dll (2017-02-03 18:14:18 UTC)
    HDCD decoder 1.19
foo_input_dvda.dll (2020-04-15 14:32:40 UTC)
    DVD-Audio Decoder 0.5.1
foo_input_monkey.dll (2019-11-20 11:13:18 UTC)
    Monkey's Audio Decoder 2.3.1
foo_input_sacd.dll (2020-05-01 18:42:26 UTC)
    Super Audio CD Decoder 1.2.3
foo_input_std.dll (2020-09-25 11:48:12 UTC)
    FFmpeg Decoders 4.3.1
    Standard Input Array 1.6.1
foo_out_wasapis.dll (2020-08-05 04:46:58 UTC)
    WASAPI shared output 0.6.14
foo_rgscan.dll (2020-09-25 11:47:58 UTC)
    ReplayGain Scanner 1.6.1
foo_scrobble.dll (2018-08-18 01:52:58 UTC)
    Scrobble 1.3.1
foo_spider_monkey_panel.dll (2020-07-18 20:13:40 UTC)
    Spider Monkey Panel 1.3.1
foo_ui_columns.dll (2020-09-04 04:55:18 UTC)
    Columns UI 1.6.0
foo_ui_std.dll (2020-09-25 11:48:08 UTC)
    Default User Interface 1.6.1
foo_unpack.dll (2020-09-25 11:47:56 UTC)
    ZIP/GZIP/RAR/7-Zip Reader 1.9

Started after I updated to the latest master, already completely nuked my georgia and tried reinstalling but it didn't fix the issue. Is this issue perhaps related to the commit that added defaults.js? Sorry for the poor formatting.

**Comment by kbuffington** [comment]
Yeah, should be good now. _Usually_ latest master is safe to use, but I had to reboot my computer earlier today with an unpushed change and then didn't get back to it until now. Try again and everything should be good.

**Comment by ghost** [comment]
Yup, it's working again. Thank you for fixing the issue!
