### ISSUE TITLE
Possible issue - gridEntry is undefined in settings.js

### ISSUE THREAD

**Issue by dwmartin0906** [kbuffington/Georgia#64]
This may be my error, but I didn't change anything in settings.js except for two entries under pref.add_properties that have been there for months.  After updating to your newest version from a couple of hours ago I am now getting this error message.  The previous version from several hours ago worked fine after I added defaults.js. to georgia-theme.js.  Any idea what I might have done wrong this time?  My previous issue on the timeline  was due to 2 lines of code I had commented out for no explicable reason.

Error: Spider Monkey Panel v1.3.2-beta+f0830b60 (Georgia v2.0.0-beta1 by Mordred)
include failed:
gridEntry is undefined

File: settings.js
Line: 188, Column: 48

Stack trace:
  replaceGridEntry/entryIdx<@settings.js:188:48
  replaceGridEntry@settings.js:188:25
  migrateCheck@settings.js:207:5
  @settings.js:148:1
  loadAsyncFile/</<@georgia-theme.js:9:13

**Comment by kbuffington** [comment]
That.... doesn't make a lot of sense. The only place `gridEntry` is referenced in the entire code base is here:
```
const entryIdx = grid.findIndex(gridEntry => gridEntry.label.toLowerCase() === label.toLowerCase());
```
And gridEntry is explicitly local to the anon function created by `findIndex`. It _can't_ be undefined unless there's a bug with SMP? I see you're on the 1.3.2b, and I'm on 1.3.1. I need to sleep but I might try this later.  @TheQwertiest any ideas?

Can you attach the georgia-config.jsonc file that isn't working correctly to this issue? Maybe the parse is failing? I'm very confused. The upgrade flow is triggered by the version in the first line of that file. You can skip the upgrade by setting the value manually to 2.0.0-beta2. And you can force it to happen, by setting it back to 2.0.0-beta1, and reloading the theme. That's the best way to try and reproduce this issue. You can also just delete the config file and it will skip the upgrade as well.

**Comment by TheQwertiest** [comment]
No idea =)
Need a repro script.

**Comment by dwmartin0906** [comment]
It's working now.  First I reverted back to SMP 1.3.1, but that didn't help.  Then I discovered that settings.js had 2.0.0-beta2, but georgia-config.jsonc had 2.0.0-beta1.  I changed it to 2.0.0-beta2 and that seemed to fix it.  I hadn't changed either one previously, so I don't know how they got out of sync. I didn't think to check these before because, frankly, I just thought they were comments.  If you can think of anything I may have done to cause this, please let me know.  Thank you very much for your help.

**Comment by kbuffington** [comment]
After sleeping a bit I just realized what the problem must be. I'm betting you have/had a trailing comma at the end of the grid array definition. That'd be an undefined entry in the array so it'd still call the anon function and would cause your error.

Typescript doesn't allow that to happen: it strips trailing, entries but I'm guessing that plain JavaScript doesn't.

**Comment by kbuffington** [comment]
Double comma could also force this to happen.

**Comment by kbuffington** [comment]
Well, both those situations cause `JSON.parse` errors. Somehow you were getting an undefined value in the middle of your array. That should be fixed now, but there are probably other areas that would crash if that situation arises again.
