### ISSUE TITLE
georgia.txt link not valid

### ISSUE THREAD

**Issue by drgazelle** [kbuffington/Georgia#67]
When attempting to install Georgia for the first time I realized the link for georgia.txt is no longer valid, I even tried the direct link from within the readme. I then tried to recreate the code from the given image:

// ==PREPROCESSOR== 
// @name "Georgia"
// @author "Mordred" 

// @import "%fb2k_profile_path%georgia\js\polyfills.js"
// @import "%fb2k_profile_path%georgia\js\helpers.js"
// @import "%fb2k_profile_path%georgia\js\hyperlinks.js"
// @import "%fb2k_profile_path%georgia\js\CaTRoX_OWR\js_marc2003\js\lodash.min.js"
// @import "%fb2k_profile_path%georgia\js\CaTRoX_OWR\js_marc2003\js\helpers.js"
// @import "%fb2k_profile_path%georgia\js\CaTRoX_QWR\Common.js"
// @import "%fb2k_profile_path%georgia\js\CaTRoX_QWR\Utility_LinkedList.js"
// @import "%fb2k_profile_path%georgia\js\globals.js"
// @import "%fb2k_profile_path%georgia\js\CaTRoX_QWR\Control_ContextMenu.js"
// @import "%fb2k_profile_path%georgia\js\CaTRoX_OWR\Control_HtaMsgBox.js"
// @import "%fb2k_profile_path%georgia\js\CaTRoX_OWR\Control_HtaGroupPresetsMngr.js"
// @import "%fb2k_profile_path%georgia\js\CaTRoX_QWR\Control_Scrollbar.js"
// @import "%fb2k_profile_path%georgia\js\CaTRoX_QWR\Control_List.js"
// @import "%fb2k_profile_path%georgia\js\CaTRoX_QWR\Panel_Playlist.js"
// @import "%fb2k_profile_path%georgia\js\CaTRoX_QWR\Control_Button.js"
// @import "%fb2k_profile_path%georgia\js\color.js"
// @import "%fb2k_profile_path%georgia\js\themes.js"
// @import "%fb2k_profile_path%georgia\js\Image_Caching.js"
// @import "%fb2k_profile_path%georgia\js\georgia-main.js"
// @import "%fb2k_profile_path%georgia\js\lyrics.js"
// @feature "dragdrop"
// ==/PREPROCESSOR==

Though I assume it is caused by an error from my copying, I couldn't get past step 9 due to an issue with helpers.js in line 2: 
const lodash = _.noConflict();

**Comment by kbuffington** [comment]
It seems you downloaded the Repo, which means you're looking at the beta version and the install directions are a little different.

You can look at the [detailed instructions under the beta1](https://github.com/kbuffington/Georgia/releases) release OR download the [1.1.10 release](https://github.com/kbuffington/Georgia/releases/tag/1.1.10) and follow the same instructions you were looking at.

**Comment by drgazelle** [comment]
That fixed my issue, thank you so much!
