### ISSUE TITLE
Georgia v2.0.0-beta2

### ISSUE THREAD

**Issue by Zephyr0ck** [kbuffington/Georgia#68]
Hi, I'm using this topic to say that foobar2000 with Georgia is now faster (at first run and opening foobar2000).

https://user-images.githubusercontent.com/66889502/105398731-50bc7380-5be8-11eb-9a12-ea356950d27a.mp4

Thanks for all the effort, dedication and work with this amazing skin for foobar2000

Sorry if it's not the right place for post this.

**Comment by kbuffington** [comment]
That's awesome! Yours loads a _lot_ faster than mine. Is your library on an SSD or just not that big?

Two things I noticed from that video:
* There should be an artist image for Decapitated. Can't tell if the theme thought there wasn't enough room to display it or if you don't have the images? 
* Your fonts also seem different: did you change the fonts, or just not install the included ones yet?

**Comment by Zephyr0ck** [comment]
> That's awesome! Yours loads a _lot_ faster than mine. Is your library on an SSD or just not that big?
> 
> Two things I noticed from that video:
> 
> * There should be an artist image for Decapitated. Can't tell if the theme thought there wasn't enough room to display it or if you don't have the images?
> * Your fonts also seem different: did you change the fonts, or just not install the included ones yet?

Hi!

my library is stored in a HDD External 1TB with up to 650GB of Music (**.flac**, **.wav**, **.ape**, **.wv**, **Hi-Res**).

about the artist's logo I forgot to modify this line:

`pref.logo_hq = fb.ProfilePath + 'images/artistlogos/'; // location of High-Qualiy band logos for the bottom left corner`

to this:

`pref.logo_hq = fb.ProfilePath + 'georgia/images/artistlogos/'; // location of High-Qualiy band logos for the bottom left corner`

for the font i have changed font into **georgia-main.js**

Thanks for develop this insane skin!

**Comment by ghost** [comment]
Would you mind sharing the code for the codec data string? It looks pretty nice.
