### ISSUE TITLE
Library Tree Zoom and Scaling Issues

### ISSUE THREAD

**Issue by 3vilgenius** [kbuffington/Georgia#7]
here is another bug I found on top of the ones involving scaling issues with the library tree. There other library or playlist manager thing constantly zooms in every single time I click full screen on foobar while still having the playlist manager selected and it will not zoom back out or scale back down. Here's is a picture, although it doesn't look like much because it zoomed in soo much towards the top left corner of that window, that it just looks like a black box now. https://imgur.com/gallery/PBp5gd7 https://imgur.com/gallery/WLIB9IZ edit another clearer example of the first issue https://imgur.com/a/C2vW9zU .

Also Clicking Library Settings - > Reset library zoom did not change anything.

**Comment by Marmizo** [comment]
Hi, I have the same zoom issue, does anyone have an idea ?

https://imgur.com/a/Hu85XHg

**Comment by kbuffington** [comment]
@Marmizo Hold down Ctrl+Alt while hovering the mouse over the Library Tree, and then scroll your mouse wheel to zoom in and out. 

If you can't get that to work, try Library Settings -> Reset Library Zoom. @3vilgenius said that didn't work for him, but I'd have to look at why it's not. Unfortunately my PC is broken at the moment so I can't do any work on it right now.

You can also try right clicking on the background of the theme (not on the artwork or library) and opening up the theme Properties page, and then clearing all properties using the button at the bottom. The theme should reload and your library should be back to normal.

**Comment by Marmizo** [comment]
@kbuffington Thanks you for your quick reply.
Unfortunately Ctrl + Alt does not work, worse, the zoom increases when I scroll the wheel in both directions.
Library Settings -> Reset Zoom Library does not work either.
So I manually change the font size in the panel properties.

**Comment by asofnowyoudie** [comment]
I have a similar issue but for the Playlist tab, where the font size is too large: https://imgur.com/KavGfQg. This issue does not appear when not in "4k" mode, but when near fullscreen or fullscreen on a 4K monitor, it occurs. This issue also does not occur on the library view. 

I've modified some of the .js files to get the Georgia theme exactly as I want it, and have disabled 4K mode (and the check for 4K mode) to the best of my ability in georgia-main.js, but it seems like this bug still occurs in the Playlist view. I've been searching for the line of code where Georgia enlarges the text only in the Playlist view but I have not been able to find it. The Ctrl+Alt trick also doesn't work in the Playlist view (it does work in the Library view). 

I also wanted to say thank you very much to @kbuffington. This is an amazing theme and it has got me in love with my music library again.

**Comment by kbuffington** [comment]
@asofnowyoudie Shit, that's not great.

The issue there in the Playlist tab is that the rows have a height value associated with them as well. Right click on the dark bar at the top, select Properties, and then scroll down and adjust the user.row.height until it's to your liking:

![image](https://user-images.githubusercontent.com/2282004/51354694-055faf80-1a7a-11e9-8ada-6ed2c3c5e109.png)

I didn't write the Playlist (@TheQwertiest) or the Library Tree (WillB)... just crammed them into the theme and did some editing so they worked, so they don't have the exact same feature set, sadly.

**Comment by asofnowyoudie** [comment]
@kbuffington Wow! Thank you for such a quick reply!

That does seem to fix it. I've changed the user.row.height value to 30. The only problem now is that when the window is smaller there is quite a lot of padding between rows, which isn't major at all. 

Just one more question, is there a way to make the text in the Playlist pane not get larger when it goes into "4K mode" (which I disabled...)? From this album, you can see that when the window is smaller, the text size is probably around 12, but when maximized the text size gets larger in the playlist for some reason, but nowhere else in Foobar (not even the library): https://imgur.com/a/bn7O2xv. I'd much rather the text size stay 12 when the window is maximized.

Thanks again for all your work. Is there a way I can send you a small donation to say thanks?

**Comment by kbuffington** [comment]
@asofnowyoudie From looking at your pictures and your description it sounds like the 4k detection stuff is still taking precedence. I'll add a way to defeat this in the future, but for now, go to line 1461 of georgia-main.js and replace the entire contents of that function with:

    function checkFor4k(w) {
    	is_4k = false;
    }

And let me know if that fixes the problem. If it does, you might find you need to change back the user.row.height value again though.

**Comment by asofnowyoudie** [comment]
@kbuffington Unfortunately, the font still increases in size on a 4k display even with that tweak. I actually modified that line to be:
```
function checkFor4k(w) {
	if (w > 3000) {
		is_4k = false;
	} else {
		is_4k = false;
	}
	if (last_size !== is_4k) {
		sizeInitialized = false;
	}
}
```
before I began commenting in this thread, so it seems that the scaling isn't due to that line of code which is really weird. I've scoured georgia-main.js for any instances of '4k' and have modified code to see if it made a change and still couldn't figure it out.

Thanks for all your help anyway, and I'll be using the change to user.row.height to just make sure the lines don't overlap for the time being.

**Comment by kbuffington** [comment]
I've got replacement parts coming in for my computer this weekend, so hopefully I'll be back up and running and able to debug and fix this for you shortly.

**Comment by kbuffington** [comment]
@3vilgenius @Marmizo @asofnowyoudie 
I believe version 1.0.1 fixes all issues brought up in this thread. Please let me know if something still isn't working.

Note if on initial load things still look bad, I recommend reseting Library Tree Zooming again (it'll do something now) and then reloading the theme just for good measure.

**Comment by Marmizo** [comment]
It works perfectly for me, thank you !

**Comment by asofnowyoudie** [comment]
Fixed all my issues as well, many thanks!

**Comment by kbuffington** [comment]
Thanks guys, closing.

**Comment by 3vilgenius** [comment]
thanks buff daddy
