### ISSUE TITLE
Lyrics File Naming Scheme 

### ISSUE THREAD

**Issue by VedanshGoenka** [kbuffington/Georgia#70]
First of all, I'd like to thank @kbuffington for this amazing skin and all the work that you have put into it. 

I'd call this more of a feature request than a bug; all of my .flac files are tagged as follows in musicbrainz picard. 

`$if($gt(%totaldiscs%,1),$if(%discnumber%,%discnumber%_,),) $num(%tracknumber%,2) - %title%`

This outputs to either:

01 - Give Life Back to Music.flac
or for multi-disk albums
1_ 01 - Funeral.flac

In the same folder as my music, I have lyrics files (not nested). These are named as follows:

Give Life Back to Music.lrc
and 
Funeral.lrc

The lyrics aren't detected by georgia unless I change the filename for the lyrics file to:
01 - Give Life Back to Music.**lrc**
or for multi-disk albums
1_ 01 - Funeral.**lrc**

I have over 2000 songs and ~1500 lyrics files. Is there a way in the lyrics.js file to use the trackname as an option rather than the filename? 
Possibly adding something here: (Line 277-291)

```
  /**
   * @param {string} path
   * @param {string} filename
   */
  checkFile(path, filename) {
    var found = true;
    if (IsFile(path + filename + ".lrc")) {
      this.fileName = path + filename + ".lrc";
    } else if (IsFile(path + filename + ".txt")) {
      this.fileName = path + filename + ".txt";
    } else {
      found = false;
    }
    return found;
  }

```

I'm not experienced enough with js to do this myself. 

I've asked a lot of my friends (all of whom LOVE georgia) and they have similar renaming practices (their lyrics files are named the same, but their tracknames are named with album titles/artists).

Thanks Again for this AWESOME skin!!!

-Vedansh

**Comment by kbuffington** [comment]
Very good suggestion. I'll be adding user customizable patterns to the config file in beta 4 or in the final 2.0 release.

**Comment by kbuffington** [comment]
`lyricFilenamePatterns` were added to georgia-config.jsonc in beta4.
