### ISSUE TITLE
Georgia v2.0.0 beta3

### ISSUE THREAD

**Issue by Zephyr0ck** [kbuffington/Georgia#71]
Thank you @**kbuffington**!

The new version is fast and stable, so far I haven't had any problems. 

I made new icons for **Playlist**, **Library**, **Lyrics**, **Properties**, **Rating**, **Settings**.

https://user-images.githubusercontent.com/66889502/106673893-fd4b0d80-6577-11eb-9955-3cc0b70d14cc.mp4

**Comment by kbuffington** [comment]
Can you attach a zip with those new icons? They look pretty good, and I might want to switch to using them or at least provide them as an option.

**Comment by Zephyr0ck** [comment]
> Can you attach a zip with those new icons? They look pretty good, and I might want to switch to using them or at least provide them as an option.

Yes! can i send you via email. You could give me any email to send them?

**Comment by kbuffington** [comment]
You can just drag and drop files into this ticket. That way I don't have to post my private e-mail -- or you can message me on reddit or H-A and I'll send it to you there.

**Comment by Zephyr0ck** [comment]
> 
> 
> You can just drag and drop files into this ticket. That way I don't have to post my private e-mail -- or you can message me on reddit or H-A and I'll send it to you there.

done, i've sent a PM at H-A

**Comment by kbuffington** [comment]
Thanks. Working on integrating these now.
