### ISSUE TITLE
Two dates separated by / on v2.0.0-beta3

### ISSUE THREAD

**Issue by Zephyr0ck** [kbuffington/Georgia#72]
Hello again!

As always thanks in advance @kbuffington for this amazing theme for foobar2000.

I have a question/request regarding the date, in **.flac** / **.wav** / **.ape** / **.wv** and **.CUE** files some of my files have two dates (Release date and Re-release/Reissue date) but in Georgia they are not shown, is there a way to fix it? 

Date on Properties in .FLAC file
![01](https://user-images.githubusercontent.com/66889502/106817227-2fbe3e80-663c-11eb-8d77-7fec4d5dfcab.PNG)

Date on .CUE file
![02](https://user-images.githubusercontent.com/66889502/106817231-3056d500-663c-11eb-9586-d3eddb932df7.PNG)

Georgia does not show the date
![03](https://user-images.githubusercontent.com/66889502/106817232-30ef6b80-663c-11eb-969b-659fcc84c4ae.PNG)

I appreciate all your effort and hard work on this sublime theme @kbuffington, Thank you!

**Comment by kbuffington** [comment]
What's the actual name of that field which properties shows as Date released? The date in the upper right corresponds to title_format_strings.year in the config file (someday I'll document this stuff better). You could probably just delete `$year(` and `)` from around the `$if3` and my guess is it'd work. If the FLAC is using a field that isn't one of the four listed you can just add it to the list.

Let me know if there are any issues, because it's possible that `.year` is used elsewhere besides there and in the right of playlist headers and it might require a four-digit year.

**Comment by Zephyr0ck** [comment]
> What's the actual name of that field which properties shows as Date released? The date in the upper right corresponds to title_format_strings.year in the config file (someday I'll document this stuff better). You could probably just delete `$year(` and `)` from around the `$if3` and my guess is it'd work. If the FLAC is using a field that isn't one of the four listed you can just add it to the list.
> 
> Let me know if there are any issues, because it's possible that `.year` is used elsewhere besides there and in the right of playlist headers and it might require a four-digit year.

on .CUE file: REM DATE
on .flac file: date 

both cases does not show the date even in the playlist 

![Capture](https://user-images.githubusercontent.com/66889502/106827326-45d4fa80-664e-11eb-9fab-cf406eaa435f.PNG)

**Comment by kbuffington** [comment]
Shit dude, I apologize. I didn't ever see your response. Can you attach a cue file for me? I want to test some things out and I don't want to guess at the format.

**Comment by Zephyr0ck** [comment]
> 
> 
> Shit dude, I apologize. I didn't ever see your response. Can you attach a cue file for me? I want to test some things out and I don't want to guess at the format.

Don't worry bro, well there's the .CUE file

[Eaten Back To Life.zip](https://github.com/kbuffington/Georgia/files/5952539/Eaten.Back.To.Life.zip)

**Comment by kbuffington** [comment]
Finally got around to testing this out. Dates formatted "1980 / 1990" were showing up in the playlist for me, but not in the upper right corner while playing the song. To fix that I just removed the `$year()` from the `title_format_strings.year` value in the config file. Didn't see any issues after making that change. Let me know if you need further help with this.

**Comment by Zephyr0ck** [comment]
> Finally got around to testing this out. Dates formatted "1980 / 1990" were showing up in the playlist for me, but not in the upper right corner while playing the song. To fix that I just removed the `$year()` from the `title_format_strings.year` value in the config file. Didn't see any issues after making that change. Let me know if you need further help with this.

Yay! it worked!

The date is now displayed in the playlist and at the top right. 
Thanks a lot for the help!

![Georgia02](https://user-images.githubusercontent.com/66889502/108003354-2a57e100-6fb8-11eb-8f70-7b69a2386020.PNG)

![Georgia01](https://user-images.githubusercontent.com/66889502/108003352-275cf080-6fb8-11eb-833e-2b25244e3185.PNG)

**Comment by kbuffington** [comment]
Thanks for the screenshot. Looks like I need to take care of the text overlap in the playlist too. I'll make a note of that.
