### ISSUE TITLE
Volume Bar in Dark Mode

### ISSUE THREAD

**Issue by smoralis** [kbuffington/Georgia#74]
When dark mode is selected the volume bar level color is to close to the dark color making it unable to see the current level.
![image](https://user-images.githubusercontent.com/3080179/109534873-7fb9e500-7ac4-11eb-9f55-f6ce41201990.png)

idx      color        bright  freq   weight
 0 rgb( 32,  43,  49)   41   16.38%   67.17
 1 rgb( 14,  26,  34)   24   15.91%   38.19
 2 rgb( 43,  55,  64)   53   11.22%   59.47
 - rgb(  8,  11,  13)   10    9.51%    grey
 - rgb( 64,  67,  71)   67    8.16%    grey
 - rgb(119, 119, 122)  119    6.90%    grey
 - rgb( 81,  83,  86)   83    5.93%    grey
 - rgb( 98, 100, 102)  100    5.36%    grey
 - rgb(137, 141, 144)  140    4.89%    grey
 9 rgb( 28,  71,  99)   66    4.01%   26.45
10 rgb(228, 236, 241)  234    3.87%    7.73
11 rgb(159, 170, 176)  167    3.49%   30.34
12 rgb(190, 205, 212)  201    3.48%   18.46
 - rgb(  0,   1,   6)    2    0.89%    grey
Selected Color: rgb(32, 43, 49)
distance from: rgb(32, 43, 49) to: rgb(50, 54, 57) = 36.954575156535086
>>> Theme primary color is too close to bg color. Tinting theme color.
distance from: rgb(43, 54, 59) to: rgb(23, 22, 25) = 90.92055254451547

**Comment by kbuffington** [comment]
Good catch. I'll use the same logic I use for the progress bar and just turn the volume fill white.

**Comment by smoralis** [comment]
Perfect !!

**Comment by kbuffington** [comment]
Fixed in 2.0.1.
