### ISSUE TITLE
Check for updated version of Georgia returns 2.0.0 instead of 2.0.1

### ISSUE THREAD

**Issue by dwmartin0906** [kbuffington/Georgia#76]
Hi.  This may not even be an issue, but when I check for an updated version I get the following console message:  Current released version of Georgia: vv2.0.0.  I expected to see version 2.0.1.  I've pasted the first couple of entries from https://api.github.com/repos/kbuffington/Georgia/tags below.  I wonder if the 2.0.1 entry should be moved to the top, but you may very well have a reason for this.  I just wanted to let you know.

{
    "name": "v2.0.0",
    "zipball_url": "https://api.github.com/repos/kbuffington/Georgia/zipball/v2.0.0",
    "tarball_url": "https://api.github.com/repos/kbuffington/Georgia/tarball/v2.0.0",
    "commit": {
      "sha": "a3f882da1996be61672256f80f802b613de237d8",
      "url": "https://api.github.com/repos/kbuffington/Georgia/commits/a3f882da1996be61672256f80f802b613de237d8"
    },
    "node_id": "MDM6UmVmMTMwNTM1ODE1OnJlZnMvdGFncy92Mi4wLjA="
  },
  {
    "name": "2.0.1",
    "zipball_url": "https://api.github.com/repos/kbuffington/Georgia/zipball/2.0.1",
    "tarball_url": "https://api.github.com/repos/kbuffington/Georgia/tarball/2.0.1",
    "commit": {
      "sha": "9f1a6b47c9edd54bd1ab271be9903ab46249c763",
      "url": "https://api.github.com/repos/kbuffington/Georgia/commits/9f1a6b47c9edd54bd1ab271be9903ab46249c763"
    },
    "node_id": "MDM6UmVmMTMwNTM1ODE1OnJlZnMvdGFncy8yLjAuMQ=="
  },

**Comment by kbuffington** [comment]
Thanks, I had tagged it incorrectly. Probably should change how the update check works to not just take the first result returned, but instead, parse all the entries and find the latest, but I'll do that another day.
