### ISSUE TITLE
Album title position 

### ISSUE THREAD

**Issue by Synkro12** [kbuffington/Georgia#77]
Hey kbuffington, first off congrats on the 2.0 release.

This enhancement would remove some double information and free up some space on the metadata grid by moving the album title above the timeline bar and removing the tracknumber and title since we already have that at the bottom, I've included a picture below.

https://imgur.com/a/5zTShI5

**Comment by kbuffington** [comment]
I've had another user request this as well. Even though the information is duplicated I like having it in both places because it's easier for me to scan with the album title as well. If I add this it would have to be an optional change. I'll put it on the list though.

**Comment by Synkro12** [comment]
Makes sense yeah, thanks for taking it into consideration!
