### ISSUE TITLE
Jscript Panel error when attempting install

### ISSUE THREAD

**Issue by VonTittyslappen** [kbuffington/Georgia#8]
Hi there

I LOVE the look of this theme from the imgur pictures I saw.

I've followed the steps as per your instructions but when I copy & paste the text from the Georgia.txt I get the following error message:-Panel v2.2.0-Beta 2 (Georgia by Mordred)
JavaScript runtime error:
Object doesn't support this property or method
File: C:\Users\Simon\AppData\Roaming\foobar2000\georgia\js\CaTRoX_QWR\Panel_Library.js
Line: 1056, Col: 1
<source text only available at compile time>

Does Foobar have to be installed as portable mode for this to work properly, or will the standard mode work fine?

Please help, not sure where I've gone wrong :(

Cheers

**Comment by kbuffington** [comment]
Can you try using an earlier version of jscript panel? I think something in v2.2.0 Beta 2 broke it.

I'd start with this one: https://github.com/marc2k3/foo_jscript_panel/releases/tag/v2.1.8
and if that doesn't work try an earlier 2.1 release.

My windows PC is broken at the moment and waiting for parts to get in so I can't debug for a few days.

**Comment by VonTittyslappen** [comment]
Hi mate

Thanks so much for replying so quickly, I shall certainly give an earlier version of jscript panel a go, fingers crossed!

Will keep you posted :]

**Comment by VonTittyslappen** [comment]
Yep, that earlier version of jscript panel did the trick, cheers! Going to give this a test run :)

**Comment by kbuffington** [comment]
Glad that fixed it for you. Once my computer is back and running I'll fix the issues with 2.2 JScript.
