### ISSUE TITLE
Volume bar text display can be difficult to see on lighter covers

### ISSUE THREAD

**Issue by dwmartin0906** [kbuffington/Georgia#81]
This isn't really an issue, but just a comment.  I really like the new volume bar text display instead of the tooltip,  but find that it can sometimes be difficult to see on lighter covers.  My solution was to match the info grid colors by adding  a background based on col.primary and using col.info_text for the text color.  I really like it, but realize it may not appeal to everyone.  I'm not asking you to change it, but just wanted to put the idea out there.  Thank you again for this great theme. 

![Screenshot_7](https://user-images.githubusercontent.com/69531982/110242138-4517d880-7f1a-11eb-8420-b0432ee58595.jpg)

**Comment by kbuffington** [comment]
I had tried it like that as well, but didn't really love the results. Did the black "border" around the white letters not work for you? I felt it was still readable even on completely white album covers, but maybe there's other combinations where it didn't work that well.

I should point out that I almost never use the volume control, so I'm kind of relying on community feedback for what works and what doesn't.

**Comment by dwmartin0906** [comment]
Thank you for getting back to me.  What's readable for most people isn't necessarily so for me because of age and complications from diabetes.  And, as you can see from the image I posted, my style preferences vary a little from yours (and probably everyone else's).  Fortunately I can make most cosmetic changes myself thanks to what I learned from studying Georgia's scripts.  You were, in effect, my java script instructor.  Thank you so much.  You can close this issue.

**Comment by kbuffington** [comment]
Is it color blindness, poor eyesight or what? A "high-contrast" version isn't a terrible idea. I may not ever meet WCAG standards, but we can try and be better. :)

**Comment by dwmartin0906** [comment]
I have diabetic retinopathy with symptoms including partial vision loss and blurriness that comes and goes.   And being almost 70 doesn't help.  I still see fairly well over all, but text can be a problem.  I use the Windows magnifier a lot.  This is why a volume text display with a colored background  and contrasting colored text works much better for me.  Thank you for asking.
