### ISSUE TITLE
Lyrics.js - Missing replacement for : (colon)

### ISSUE THREAD

**Issue by smoralis** [kbuffington/Georgia#82]
You missed a required replace for illegal character : (colon) to underscore. 

Easily fixed by adding `.replace(/:/g, '_');` 
to stripReservedChars in lyrics.js  after line 193

**Comment by kbuffington** [comment]
Copy paste error when copying the same code over from `replaceFileChars` in georgia-main.js. Good catch!

**Comment by silverwings15** [comment]
on the same topic, i'd like to report the following bug: embedded lyrics fail to display (returns No lyrics found) when word count is 190 or higher. 

edit: here's a partial song lyric with 190 words for your debugging convenience

I was more than just a coward
I was handsome too
I felt nothing when your flood came down
Holding fines that made me wonder
If the lights were wrong
With my hands that never touched no ground
When your talent is in numbers
Of the many times you're gone
I could lie I don't give up forgiving
But sometimes it's just roses
Dying too young

As I'm fencing up the hours
In the fields of red
While you think I'm on a loveless stray
In the letters from the lovers
In the land gone wrong
Explanations always written late
When your talent curse the framing
All the crying you heard sung
I could lie I don't care 'bout what's missing
But sometimes it's just roses
Dying too young
Your train of thoughts is always passing here
With its falling paint, and its broken gears
It’s the damn revelation blues when you see the path
And you know you won’t be the last
Oh Lord
Oh Lord
I was more than just a terror, I was crying too
But you showed me in the gusts between
That a wind is

**Comment by kbuffington** [comment]
What in the what. I'm probably doing something dumb. Thanks for debugging, and I'll give it a look.

**Comment by kbuffington** [comment]
Turns out, it's not related to the words at all. It's an issue with foobar, and how it handles embedded lyrics... sometimes. On some files it works fine for me and on others it never works. I added a warning to explain what you need to fix:

![image](https://user-images.githubusercontent.com/2282004/112105030-ea1ced00-8b79-11eb-8e5f-864824e31354.png)

**Comment by silverwings15** [comment]
wow great find.. what a quirky bug on foobar's end. i think the warning resolves the issue nicely, appreciate it
