### ISSUE TITLE
Feature Request: Discogs Tagger integration

### ISSUE THREAD

**Issue by mist475** [kbuffington/Georgia#83]
The discogs tagger uses different fields then the musicbrainz one. As both taggers are very popular i think this would be a welcome integration, as not every release is on musicbrainz.

**Comment by ghost** [comment]
Seconded, this would be awesome.

**Comment by kbuffington** [comment]
Can you guys list the tags you have issues with and what the Discogs equivalents are? I can add them to the default values in the config file.

**Comment by mist475** [comment]
![image](https://user-images.githubusercontent.com/70655895/110796509-50e7ff80-8278-11eb-9924-f5ada55e01f2.png)
![image](https://user-images.githubusercontent.com/70655895/110796786-a3c1b700-8278-11eb-9fa3-d4ba849114a3.png)

here are the discogs tagger typically uses which differ from musicbrainz with examples
While the id's are not that interesting to show , catalog, country, label, rating and released are.

**Comment by kbuffington** [comment]
Thanks!

Metadata grid entries can easily be edited by users now, so I'll leave that as an exercise for the reader, but I'll update the values for DISCOGS_LABEL, DISCOGS_CATALOG, and DISCOGS_COUNTRY at least. VINYL_TRACK could potentially be very useful as well. Can you share me a link to where that first screenshot came from?

**Comment by mist475** [comment]
if you have the component, right click a track --> tagging --> discogs --> edit tag-mappings:
![image](https://user-images.githubusercontent.com/70655895/110983958-c0d6b280-836a-11eb-8def-9242d7388ea6.png)

**Comment by kbuffington** [comment]
Still need to look at vinyl stuff in the future.
