### ISSUE TITLE
Foobar crashes when trying to install theme

### ISSUE THREAD

**Issue by mcookiesyum** [kbuffington/Georgia#84]
I keep getting this error when trying to install theme:

Error: Spider Monkey Panel v1.4.1 (Georgia: Georgia v2.0.0 by Mordred)
include failed:
Path does not point to a valid file: C:\Users\user\Downloads\foobar2000\profile\georgia\js\CaTRoX_QWR\lodash.min.js

File: georgia-theme.js
Line: 9, Column: 13
Stack trace:
  loadAsyncFile/</<@georgia-theme.js:9:13

I am not sure why, I made sure that is the correct path.

**Comment by kbuffington** [comment]
What path do you have specified in Spider Monkey's configuration panel? A screenshot might be helpful.

**Comment by mcookiesyum** [comment]
![unknown (3)](https://user-images.githubusercontent.com/59407081/110845154-4463a700-8278-11eb-8905-78a85c804309.png)
@kbuffington this is the path I have set

**Comment by marc2k3** [comment]
Since fb2k v1.6, clean portable installs create a `profile` folder inside the install folder. 

![Untitled](https://user-images.githubusercontent.com/62050527/111028580-6a5f8780-83ef-11eb-8195-f523295b394d.png)

This is where theme files should go, not inside the main install folder itself. This is because script helpers like `fb.ProfilePath` will point towards this new folder. The main install folder should now only contain fb2k core files.

Obviously it's still possible that some peeps will be running v1.6 or later but will have upgraded from earlier versions so will not have a `profile` folder in portable mode. This distinction needs to be made in the instructions.

**Comment by mcookiesyum** [comment]
Thank you for the help! Just to be clear, do you mean to just move the georgia folder into the profile folder? I probably messed something up somewhere, but when I try this I get a new error. 

Error: Spider Monkey Panel v1.4.1 (Georgia: Georgia v2.0.0 by Mordred)
include failed:
img is undefined

File: georgia-main.js
Line: 2743, Column: 10
Stack trace:
  createButtonObjects@georgia-main.js:2743:10
  on_size@georgia-main.js:1365:2
  on_init@georgia-main.js:1302:3
  @georgia-main.js:341:1
  loadAsyncFile/</<@georgia-theme.js:9:13
![image](https://user-images.githubusercontent.com/59407081/111044946-824c0100-8419-11eb-8ff8-1ee0e9680dd1.png)

**Comment by kbuffington** [comment]
So is your foobar install portable then?

Before doing anything else, download the new [2.0.1 version](https://github.com/kbuffington/Georgia/releases/tag/2.0.1) just so everything is up to date.

I was unaware of the new profile folder that marc2k3 was talking about, and don't have a `profile` folder in my portable setup and everything works fine. It looks from your last screenshot that the theme loaded correctly, but then there's probably something that doesn't work from that path. I'll try and do some testing today.

**Comment by kbuffington** [comment]
Just checked and if your portable install has the `profile` folder then georgia should be installed there and everything should work:

![image](https://user-images.githubusercontent.com/2282004/111076615-073b2700-84bb-11eb-89f4-659fb1b9ce30.png)

I'm seeing no issues or crashes with 2.0.1 in that location on a new portable install. I'll update the documentation when I get back from vacation.

**Comment by kbuffington** [comment]
Updated the documentation with detailed instructions for portable installs of both flavors.
