### ISSUE TITLE
Some issues with the readme doc

### ISSUE THREAD

**Issue by kazum1kun** [kbuffington/Georgia#9]
Hi, thanks for this great theme. I was reading along the installation instruction and found some issues. 

- Links to individual image pack needs to be updated, right now they all return 404
- The `foo_script_panel` dependency has been updated to v2.2.1.1 and old versions were removed from the release page. However after some digging I found historical versions in its wiki: https://github.com/marc2k3/foo_jscript_panel/wiki/Old-Versions so maybe you want to instead point to this one?

Thanks!

**Comment by kbuffington** [comment]
Fixed the README. I've also added the latest known working version of foo_jscript to the release page so it'll always be available... although I want to encourage people to use the current version as long as there isn't an issue.
