### ISSUE TITLE
Auto display lyrics option

### ISSUE THREAD

**Issue by mortan** [kbuffington/Georgia#94]
Hi! First a big thank you for this amazing foobar theme! Would it be possible to add an option to automatically show lyrics (if available) when playing a song after a fresh foobar2000 start? Something like Options->Playlist->Display playlist on startup just for Lyrics (Options->Lyrics->Automatically display lyrics if available ?).

Kind regards

**Comment by kbuffington** [comment]
Available in 2.0.3.
