### ISSUE TITLE
Foobar can't find lyrics for song with two artist in its artist tag

### ISSUE THREAD

**Issue by BEST8OY** [kbuffington/Georgia#95]
Hi
The Problem has been described in title
these are patterns that i found in codes
`		"%title%",
		"%artist% - %title%",
		"%artist% -%title%",
		"%tracknumber% - %title%",
		"%tracknumber% - %artist% - %title%"
`
i have a song which name of song and its lrc are "Mark Ronson - Nothing Breaks Like a Heart (Acoustic Version)"
Artist tag is "Mark Ronson; Miley Cyrus" and title tag is "Nothing Breaks Like a Heart (Acoustic Version)"
So foobar can't find lyrics because of artist tag
**Is there any pattern that ignore any character, words, etc before title tag?
I like it this way
If there was a pattern like this, we don't need to write multiple patterns anymore**

**Comment by kbuffington** [comment]
I think the file would need to be named `Mark Ronson; Miley Cyrus - Nothing Breaks Like a Heart (Acoustic Version)` for it to get picked up out of the box.

You could also add a new file pattern:
`"$meta(artist, 0) - %title%"` and that would always look for just the first artist.

There's no way to always perfectly handle it since another component/program is writing the files.

**Comment by BEST8OY** [comment]
I renamed it to `Mark Ronson, Miley Cyrus - Nothing Breaks Like a Heart (Acoustic Version)` and it was okay
and adding `"$meta(artist, 0) - %title%"` caused crash with this error:
`File: Common.js
Line: 436, Column: 3
Stack trace:
  ThemeError@Common.js:436:3
  readConfiguration@configuration.js:118:10
  @settings.js:120:23
  loadAsyncFile/</<@georgia-theme.js:9:13`

**Comment by kbuffington** [comment]
The crash was on reading the config file. I'll take a look, but most likely you missed a comma on the previous line, or had an extra one.

**Comment by BEST8OY** [comment]
Yes i missed the comma :)
It fixed the problem no renaming needed anymore
Thanks a lot
