### ISSUE TITLE
Display YT Artwork

### ISSUE THREAD

**Issue by MojoBass** [kbuffington/Georgia#96]
FB 1.6.5, foo_youtube 3.7, Georgia 2.0.2:
No youtube artwork shown when Preferences->Tools->Youtube Source->Maintainance->Third-party Binaries->youtube-dl->Prefer youtube-dl over internal analyzer is switched on.
If 'Prefer youtube-dl over internal analyzer' is switched off, youtube artwork is shown as intended.

**Comment by kbuffington** [comment]
I don't believe there's anything I can do to solve this issue. If you can show me an example of another theme that works with "Prefer youtube-dl over internal analyzer" switched on, feel free to reopen and I'll investigate what they're doing differently.

**Comment by MojoBass** [comment]
Did some more research on that topic:
- the issue are the thumbnails offered by youtube
- when switched on in foo_youtube (Metadata->Album Art ->Expose Thumbnails as album art), the thumbnail with its size and format is shown in any case at Properties->Artwork->Front Cover
- I found the formats  JPEG and WebP in different yt tracks
- is seems that Georgia is displaying JPEG always correctly, WebP is not shown at all
- the Album Art/Thumbnaiils from any yt tracks are always shown correctly with the JSP script 'Album Art', see here: [https://github.com/marc2k3/foo_jscript_panel/wiki/Gallery](url)
- WilBs Biography script on SMP (v1.1.3) has same limitation as Georgia: does not display WebP format thumbnails
- It has (probably) nothing to do with 'Prefer youtube-dl over internal analyzer' switched on/off (as wrongly stated from my side)

Would be great if you could re-open the issue :-)

**Comment by kbuffington** [comment]
I did a little more digging on this. According to [TheQwertiest (and my tests today confirm)](https://hydrogenaud.io/index.php?topic=116669.msg974970#msg974970) SMP does not support WebP images. Maybe JSP does now, and it seems foobar can read them (or is getting them somehow at least), but SMP just can't read them, even using that exact AlbumArt script in SMP. Don't think there's anything that can be done unfortunately.

You could always ask in the SMP thread to see if there are any plans to change this.

**Comment by MojoBass** [comment]
ok, I will do that. Thanks very much!! And I am excited to try your new version!!
